#!/bin/bash
# Send tabiji.ai customer email via Gmail.
# Usage: send-email.sh --to EMAIL --subject SUBJECT --body-file FILE [--from NAME]
# Usage: send-email.sh --to EMAIL --subject SUBJECT --body "inline text"
#
# ⚠️ THIS IS THE ONLY WAY TO SEND TABIJI CUSTOMER ITINERARY EMAILS.
# Itinerary emails still require the deploy-token gate generated by fulfill-order.js
# after the itinerary URL returns HTTP 200.
#
# Requires: gws authenticated for psyduckler@gmail.com

set -euo pipefail

FROM_NAME="Psy / tabiji"
FROM_EMAIL="psyduckler@gmail.com"
GMAIL_ACCOUNT="${GMAIL_ACCOUNT:-psyduckler@gmail.com}"
GWS_BIN="${GWS_BIN:-gws}"
TO=""
SUBJECT=""
BODY_FILE=""
BODY_TEXT=""
DRY_RUN="false"

VERIFY_URL=""
DEPLOY_TOKEN_FILE=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --to) TO="$2"; shift 2 ;;
    --subject) SUBJECT="$2"; shift 2 ;;
    --body-file) BODY_FILE="$2"; shift 2 ;;
    --body) BODY_TEXT="$2"; shift 2 ;;
    --from) FROM_NAME="$2"; shift 2 ;;
    --from-email) FROM_EMAIL="$2"; GMAIL_ACCOUNT="$2"; shift 2 ;;
    --verify-url) VERIFY_URL="$2"; shift 2 ;;
    --deploy-token) DEPLOY_TOKEN_FILE="$2"; shift 2 ;;
    --dry-run) DRY_RUN="true"; shift ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# =====================================================================
# DEPLOY TOKEN GATE — itinerary emails REQUIRE a deploy token
# The token is generated ONLY by fulfill-order.js after confirming 200 OK.
# This prevents sub-agents from bypassing fulfill-order.js and sending
# emails before the page is live.
# =====================================================================
if [[ "$SUBJECT" == *"Itinerary"* || "$SUBJECT" == *"itinerary"* ]]; then
  if [[ -z "$DEPLOY_TOKEN_FILE" ]]; then
    echo "❌ BLOCKED: Itinerary emails require --deploy-token <file>."
    echo "   This token is generated by fulfill-order.js after verifying the page is live."
    echo "   You MUST use fulfill-order.js for itinerary fulfillment. Direct calls to send-email.sh are not allowed."
    exit 1
  fi
  if [[ ! -f "$DEPLOY_TOKEN_FILE" ]]; then
    echo "❌ BLOCKED: Deploy token file not found: $DEPLOY_TOKEN_FILE"
    echo "   The token is a one-time file created by fulfill-order.js. It may have already been consumed."
    exit 1
  fi
  # Validate token file has expected structure
  if ! python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert 'token' in d and 'httpStatus' in d and d['httpStatus']==200" "$DEPLOY_TOKEN_FILE" 2>/dev/null; then
    echo "❌ BLOCKED: Deploy token file is invalid or does not confirm HTTP 200."
    exit 1
  fi
  VERIFIED_URL=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['url'])" "$DEPLOY_TOKEN_FILE")
  echo "🔑 Deploy token valid — page verified live at $VERIFIED_URL"
  # Consume the token (one-time use)
  rm -f "$DEPLOY_TOKEN_FILE"
  echo "🔑 Token consumed (deleted)."
fi

# Legacy --verify-url fallback for non-itinerary emails
if [[ -n "$VERIFY_URL" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
  echo "🔒 Verifying $VERIFY_URL is live before sending email..."
  if ! bash "$SCRIPT_DIR/wait-for-deploy.sh" "$VERIFY_URL" 180 5; then
    echo "❌ BLOCKED: $VERIFY_URL is not live. Email NOT sent."
    exit 1
  fi
fi

if [[ -z "$TO" || -z "$SUBJECT" ]]; then
  echo "Usage: send-email.sh --to EMAIL --subject SUBJECT (--body-file FILE | --body TEXT)"
  exit 1
fi

if [[ -z "$BODY_FILE" && -z "$BODY_TEXT" ]]; then
  echo "Error: provide --body-file or --body"
  exit 1
fi

if ! command -v "$GWS_BIN" >/dev/null 2>&1; then
  echo "❌ Email send failed: gws CLI not found."
  exit 1
fi

if [[ -n "$BODY_FILE" ]]; then
  if [[ ! -f "$BODY_FILE" ]]; then
    echo "❌ Email send failed: body file not found: $BODY_FILE"
    exit 1
  fi
  BODY=$(cat "$BODY_FILE")
else
  BODY="$BODY_TEXT"
fi

COMMAND=("$GWS_BIN" gmail +send)
if [[ "$DRY_RUN" == "true" ]]; then
  COMMAND+=(--dry-run)
fi
COMMAND+=(--to "$TO" --subject "$SUBJECT" --body "$BODY" --format json)

set +e
RESPONSE=$(GOOGLE_WORKSPACE_CLI_ACCOUNT="${GOOGLE_WORKSPACE_CLI_ACCOUNT:-$GMAIL_ACCOUNT}" "${COMMAND[@]}" 2>&1)
STATUS=$?
set -e

echo "$RESPONSE"

if [[ $STATUS -eq 0 ]] && echo "$RESPONSE" | python3 -c "import json,sys; d=json.load(sys.stdin); sys.exit(0 if ('id' in d or d.get('dry_run') is True) else 1)" 2>/dev/null; then
  if [[ "$DRY_RUN" == "true" ]]; then
    echo "✅ Gmail dry run succeeded for ${GMAIL_ACCOUNT} → ${TO}"
  else
    echo "✅ Email sent successfully from ${GMAIL_ACCOUNT} to ${TO}"
  fi
else
  echo "❌ Email send failed!"
  exit 1
fi
