#!/bin/bash
# Send email via Resend API for tabiji.ai
# Usage: send-email.sh --to EMAIL --subject SUBJECT --body-file FILE [--from NAME]
# Usage: send-email.sh --to EMAIL --subject SUBJECT --body "inline text"
#
# ⚠️ THIS IS THE ONLY WAY TO SEND TABIJI CUSTOMER EMAILS.
# DO NOT use gog gmail send. DO NOT use psyduckler@gmail.com.
# All customer emails go from hello@tabiji.ai via Resend.
#
# Requires: resend-api-key in macOS Keychain

set -euo pipefail

FROM_NAME="tabiji"
FROM_EMAIL="hello@tabiji.ai"
TO=""
SUBJECT=""
BODY_FILE=""
BODY_TEXT=""

VERIFY_URL=""
DEPLOY_TOKEN_FILE=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --to) TO="$2"; shift 2 ;;
    --subject) SUBJECT="$2"; shift 2 ;;
    --body-file) BODY_FILE="$2"; shift 2 ;;
    --body) BODY_TEXT="$2"; shift 2 ;;
    --from) FROM_NAME="$2"; shift 2 ;;
    --from-email) FROM_EMAIL="$2"; shift 2 ;;
    --verify-url) VERIFY_URL="$2"; shift 2 ;;
    --deploy-token) DEPLOY_TOKEN_FILE="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# =====================================================================
# DEPLOY TOKEN GATE — itinerary emails REQUIRE a deploy token
# The token is generated ONLY by fulfill-order.js after confirming 200 OK.
# This prevents sub-agents from bypassing fulfill-order.js and sending
# emails before the page is live.
# =====================================================================
if [[ "$SUBJECT" == *"Itinerary"* || "$SUBJECT" == *"itinerary"* ]]; then
  if [[ -z "$DEPLOY_TOKEN_FILE" ]]; then
    echo "❌ BLOCKED: Itinerary emails require --deploy-token <file>."
    echo "   This token is generated by fulfill-order.js after verifying the page is live."
    echo "   You MUST use fulfill-order.js for itinerary fulfillment. Direct calls to send-email.sh are not allowed."
    exit 1
  fi
  if [[ ! -f "$DEPLOY_TOKEN_FILE" ]]; then
    echo "❌ BLOCKED: Deploy token file not found: $DEPLOY_TOKEN_FILE"
    echo "   The token is a one-time file created by fulfill-order.js. It may have already been consumed."
    exit 1
  fi
  # Validate token file has expected structure
  if ! python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert 'token' in d and 'httpStatus' in d and d['httpStatus']==200" "$DEPLOY_TOKEN_FILE" 2>/dev/null; then
    echo "❌ BLOCKED: Deploy token file is invalid or does not confirm HTTP 200."
    exit 1
  fi
  VERIFIED_URL=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['url'])" "$DEPLOY_TOKEN_FILE")
  echo "🔑 Deploy token valid — page verified live at $VERIFIED_URL"
  # Consume the token (one-time use)
  rm -f "$DEPLOY_TOKEN_FILE"
  echo "🔑 Token consumed (deleted)."
fi

# Legacy --verify-url fallback for non-itinerary emails
if [[ -n "$VERIFY_URL" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
  echo "🔒 Verifying $VERIFY_URL is live before sending email..."
  if ! bash "$SCRIPT_DIR/wait-for-deploy.sh" "$VERIFY_URL" 180 5; then
    echo "❌ BLOCKED: $VERIFY_URL is not live. Email NOT sent."
    exit 1
  fi
fi

if [[ -z "$TO" || -z "$SUBJECT" ]]; then
  echo "Usage: send-email.sh --to EMAIL --subject SUBJECT (--body-file FILE | --body TEXT)"
  exit 1
fi

if [[ -z "$BODY_FILE" && -z "$BODY_TEXT" ]]; then
  echo "Error: provide --body-file or --body"
  exit 1
fi

API_KEY=$(security find-generic-password -s "resend-api-key" -w)

if [[ -n "$BODY_FILE" ]]; then
  BODY_JSON=$(python3 -c "import json,sys; print(json.dumps(open(sys.argv[1]).read()))" "$BODY_FILE")
else
  BODY_JSON=$(python3 -c "import json,sys; print(json.dumps(sys.argv[1]))" "$BODY_TEXT")
fi

SUBJECT_JSON=$(python3 -c "import json,sys; print(json.dumps(sys.argv[1]))" "$SUBJECT")

RESPONSE=$(curl -s -X POST https://api.resend.com/emails \
  -H "Authorization: Bearer $API_KEY" \
  -H "Content-Type: application/json" \
  -d "{
    \"from\": \"${FROM_NAME} <${FROM_EMAIL}>\",
    \"to\": [\"${TO}\"],
    \"subject\": ${SUBJECT_JSON},
    \"text\": ${BODY_JSON}
  }")

echo "$RESPONSE"

# Check for errors
if echo "$RESPONSE" | python3 -c "import json,sys; d=json.load(sys.stdin); sys.exit(0 if 'id' in d else 1)" 2>/dev/null; then
  echo "✅ Email sent successfully from ${FROM_EMAIL} to ${TO}"
else
  echo "❌ Email send failed!"
  exit 1
fi
