from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'find' / 'destinations.json'
FALLBACK_PHOTO = 'https://img.tabiji.ai/owl-logo.png'

ADDITIONS = [
  {'name':'Chile','region':'South America','continent':'South America','budget':'$$','season':'Sep–Nov, Mar–May','vibes':['Nature','Adventure','Food'],'travel':['road-trip','wine','adventure'],'pitch':'A long, absurdly varied country where deserts, vineyards, lakes, and Patagonia all compete for trip-planning attention.'},
  {'name':'Argentina','region':'South America','continent':'South America','budget':'$$','season':'Sep–Nov, Mar–May','vibes':['Food','Nature','Cultural'],'travel':['food','road-trip','couples'],'pitch':'Steakhouses, wine country, big-city culture, and southern landscapes dramatic enough to justify the airfare.'},
  {'name':'South Africa','region':'Southern Africa','continent':'Africa','budget':'$$','season':'Sep–Nov, Mar–May','vibes':['Nature','Adventure','Food'],'travel':['safari','road-trip','wine'],'pitch':'One of travel’s strongest all-rounders: cities, coast, wine country, wildlife, and serious value if you plan well.'},
  {'name':'Tunisia','region':'North Africa','continent':'Africa','budget':'$','season':'Mar–May, Sep–Nov','vibes':['Beach','Cultural','Unfrequented'],'travel':['budget','history','beach'],'pitch':'Roman ruins, medinas, and Mediterranean coastlines with far less tourist drag than the region’s headliners.'},
  {'name':'French Polynesia','region':'South Pacific','continent':'Oceania','budget':'$$$$','season':'May–Oct','vibes':['Beach','Luxury','Romantic'],'travel':['honeymoon','luxury','beach'],'pitch':'Lagoons, overwater stays, and the exact sort of blue-water fantasy people mean when they say bucket-list island trip.'},
  {'name':'Panama','region':'Central America','continent':'North America','budget':'$$','season':'Dec–Apr','vibes':['Beach','City','Adventure'],'travel':['beach','road-trip','family'],'pitch':'A compact crossover trip: modern capital, Caribbean islands, Pacific surf, and rainforest all in one country plan.'},
  {'name':'Uruguay','region':'South America','continent':'South America','budget':'$$$','season':'Nov–Mar','vibes':['Beach','Relaxation','Food'],'travel':['couples','wine','road-trip'],'pitch':'South America’s calmer coastal play, with beach towns, good beef, and a noticeably lower-friction travel rhythm.'},
  {'name':'Serbia','region':'Balkans','continent':'Europe','budget':'$','season':'Apr–Jun, Sep–Oct','vibes':['City','Nightlife','Cultural'],'travel':['budget','weekend','history'],'pitch':'A high-value Balkans pick for nightlife, river cities, and a travel scene that still feels undercalled.'},
  {'name':'Slovakia','region':'Central Europe','continent':'Europe','budget':'$$','season':'May–Sep, Dec','vibes':['Nature','Cultural','Unfrequented'],'travel':['budget','hiking','road-trip'],'pitch':'Castle towns and mountain landscapes with more payoff and less crowd pressure than its neighbors.'},
  {'name':'Estonia','region':'Baltics','continent':'Europe','budget':'$$','season':'May–Sep','vibes':['City','Design','Nature'],'travel':['solo','design','weekend'],'pitch':'Digital-state efficiency, good coffee, and Baltic coastline that makes a Tallinn-plus-nature trip easy to sell.'},
  {'name':'Latvia','region':'Baltics','continent':'Europe','budget':'$$','season':'May–Sep','vibes':['City','Nature','Cultural'],'travel':['budget','weekend','solo'],'pitch':'Art nouveau Riga, pine-backed beaches, and a Baltic capital-country combo with lighter tourist pressure.'},
  {'name':'Finland','region':'Nordics','continent':'Europe','budget':'$$$','season':'Jun–Aug, Dec–Mar','vibes':['Nature','Design','Relaxation'],'travel':['outdoors','design','family'],'pitch':'Saunas, lake country, Lapland winter light, and a national talent for making quiet feel aspirational.'},
  {'name':'Malta','region':'Mediterranean','continent':'Europe','budget':'$$','season':'Apr–Jun, Sep–Oct','vibes':['Beach','Cultural','Relaxation'],'travel':['history','couples','family'],'pitch':'A small-island layup: golden-stone towns, clear water, and enough history to make a beach trip feel smarter.'},
  {'name':'Cyprus','region':'Eastern Mediterranean','continent':'Europe','budget':'$$','season':'Apr–Jun, Sep–Oct','vibes':['Beach','Relaxation','Cultural'],'travel':['family','road-trip','beach'],'pitch':'Warm-water beaches, mountain villages, and an easy Mediterranean trip that stays more practical than precious.'},
  {'name':'Bulgaria','region':'Balkans','continent':'Europe','budget':'$','season':'May–Sep, Dec–Mar','vibes':['Cultural','Nature','Budget'],'travel':['budget','road-trip','ski'],'pitch':'A strong-value European sleeper for city breaks, monasteries, mountains, and Black Sea summer add-ons.'},
  {'name':'Armenia','region':'Caucasus','continent':'Asia','budget':'$','season':'May–Jun, Sep–Oct','vibes':['Cultural','Nature','Unfrequented'],'travel':['history','budget','road-trip'],'pitch':'Stone monasteries, mountain roads, and a distinctly deep-history trip with far less tourism noise.'},
  {'name':'Saudi Arabia','region':'Middle East','continent':'Asia','budget':'$$$','season':'Nov–Mar','vibes':['Modern','Cultural','Adventure'],'travel':['luxury','history','road-trip'],'pitch':'A fast-opening destination where desert landscapes, heritage sites, and mega-project curiosity now matter in planning.'},
  {'name':'Bahrain','region':'Middle East','continent':'Asia','budget':'$$$','season':'Nov–Mar','vibes':['City','Luxury','Stopover'],'travel':['stopover','luxury','weekend'],'pitch':'A compact Gulf stopover with easy logistics, better food than expected, and enough culture to justify a few nights.'},
  {'name':'Kazakhstan','region':'Central Asia','continent':'Asia','budget':'$$','season':'May–Sep','vibes':['Nature','Adventure','Unfrequented'],'travel':['adventure','road-trip','offbeat'],'pitch':'Steppe scale, mountain access, and one of Central Asia’s easiest entries into big-landscape travel.'},
  {'name':'Guangzhou','region':'China','continent':'Asia','budget':'$$','season':'Oct–Dec','vibes':['City','Food','Modern'],'travel':['food','business','shopping'],'pitch':'Cantonese food depth alone justifies the stop, with a huge southern-China city energy behind it.'},
  {'name':'Chongqing','region':'China','continent':'Asia','budget':'$$','season':'Mar–May, Oct–Nov','vibes':['City','Food','Modern'],'travel':['food','solo','offbeat'],'pitch':'Mountain megacity, neon river views, and hot pot intensity strong enough to give the place real personality.'},
  {'name':'Qingdao','region':'China','continent':'Asia','budget':'$$','season':'May–Oct','vibes':['Beach','City','Food'],'travel':['food','weekend','beer'],'pitch':'A breezier Chinese city break with seafood, beaches, and enough German-era leftovers to keep it distinct.'},
  {'name':'Harbin','region':'China','continent':'Asia','budget':'$$','season':'Dec–Feb','vibes':['City','Cultural','Photography'],'travel':['photography','weekend','history'],'pitch':'An ice-festival headline city with Russian-flavored architecture and a rare China-in-deep-winter trip profile.'},
  {'name':'Guilin','region':'China','continent':'Asia','budget':'$$','season':'Apr–May, Sep–Oct','vibes':['Nature','Relaxation','Photography'],'travel':['photography','couples','road-trip'],'pitch':'Karst peaks and river scenery that still feel improbably cinematic even after years of seeing them online.'},
  {'name':'Yangshuo','region':'China','continent':'Asia','budget':'$$','season':'Apr–May, Sep–Oct','vibes':['Nature','Adventure','Relaxation'],'travel':['adventure','couples','photography'],'pitch':'One of China’s cleanest scenic bases for river days, cave rides, and karst landscapes at a slower pace.'},
  {'name':'Seminyak','region':'Bali','continent':'Asia','budget':'$$$','season':'May–Sep','vibes':['Beach','Luxury','Nightlife'],'travel':['friends','luxury','beach'],'pitch':'Bali’s polished villa-and-dining zone, built for stylish short stays with minimal logistical friction.'},
  {'name':'Uluwatu','region':'Bali','continent':'Asia','budget':'$$$','season':'May–Sep','vibes':['Beach','Surf','Luxury'],'travel':['surf','couples','luxury'],'pitch':'Clifftop views, destination beach clubs, and some of Bali’s best surf wrapped in a more dramatic setting.'},
  {'name':'Nusa Penida','region':'Indonesia','continent':'Asia','budget':'$$','season':'May–Sep','vibes':['Beach','Adventure','Nature'],'travel':['island-hopping','photography','couples'],'pitch':'Day-trip famous for a reason: wild cliff scenery, bright water, and a much rougher-edged Bali add-on.'},
  {'name':'Labuan Bajo','region':'Indonesia','continent':'Asia','budget':'$$','season':'Apr–Nov','vibes':['Beach','Adventure','Nature'],'travel':['liveaboard','island-hopping','adventure'],'pitch':'The Komodo gateway that matters because boats, reefs, and dragon-country itineraries start here.'},
  {'name':'Bromo','region':'Java','continent':'Asia','budget':'$','season':'May–Oct','vibes':['Adventure','Nature','Photography'],'travel':['adventure','photography','road-trip'],'pitch':'A sunrise-volcano classic that earns the cliché: ash plains, crater views, and genuinely alien scenery.'},
  {'name':'Rishikesh','region':'Uttarakhand','continent':'Asia','budget':'$','season':'Oct–Apr','vibes':['Spiritual','Nature','Adventure'],'travel':['budget','adventure','solo'],'pitch':'Part pilgrimage town, part yoga base, part river-rafting hub — enough range to support very different India trips.'},
  {'name':'Jodhpur','region':'Rajasthan','continent':'Asia','budget':'$$','season':'Oct–Mar','vibes':['Cultural','City','Photography'],'travel':['history','photography','couples'],'pitch':'The blue city delivers on visuals, but the fort, food, and desert-gateway value keep it from being just a color story.'},
  {'name':'Amritsar','region':'Punjab','continent':'Asia','budget':'$','season':'Oct–Mar','vibes':['Cultural','Spiritual','Food'],'travel':['history','food','budget'],'pitch':'The Golden Temple is reason enough, but Amritsar also hits hard on food and partition-history weight.'},
  {'name':'Leh','region':'Ladakh','continent':'Asia','budget':'$$','season':'Jun–Sep','vibes':['Nature','Adventure','Unfrequented'],'travel':['road-trip','adventure','photography'],'pitch':'High-altitude monasteries, cinematic roads, and one of India’s clearest big-landscape payoff trips.'},
  {'name':'Darjeeling','region':'West Bengal','continent':'Asia','budget':'$$','season':'Mar–May, Oct–Dec','vibes':['Nature','Relaxation','Cultural'],'travel':['tea','couples','photography'],'pitch':'Tea estates, Himalayan views, and colonial-era mountain-town atmosphere with real trip-shaping charm.'},
  {'name':'Kochi','region':'Kerala','continent':'Asia','budget':'$$','season':'Nov–Feb','vibes':['Cultural','Food','Relaxation'],'travel':['food','couples','history'],'pitch':'A softer South India coastal city with spice-trade layers, art spaces, and easy access to Kerala add-ons.'},
  {'name':'Munnar','region':'Kerala','continent':'Asia','budget':'$$','season':'Sep–Mar','vibes':['Nature','Relaxation','Romantic'],'travel':['couples','road-trip','photography'],'pitch':'Tea hills, cooler air, and one of India’s easiest scenic cool-downs after hotter, louder routes.'},
  {'name':'Koh Tao','region':'Thailand','continent':'Asia','budget':'$$','season':'Jan–Sep','vibes':['Beach','Adventure','Relaxation'],'travel':['diving','couples','beach'],'pitch':'A compact Thai island that keeps winning on easy diving access and just-enough infrastructure.'},
  {'name':'Koh Phangan','region':'Thailand','continent':'Asia','budget':'$$','season':'Jan–Sep','vibes':['Beach','Nightlife','Relaxation'],'travel':['friends','beach','couples'],'pitch':'Yes, the Full Moon party, but also surprisingly strong bays, cafes, and longer-stay island appeal.'},
  {'name':'Ayutthaya','region':'Thailand','continent':'Asia','budget':'$','season':'Nov–Feb','vibes':['Cultural','City','Relaxation'],'travel':['history','day-trip','budget'],'pitch':'Ruined capitals and temple silhouettes that make this one of Thailand’s easiest history-forward add-ons.'},
  {'name':'Khao Sok National Park','region':'Thailand','continent':'Asia','budget':'$$','season':'Dec–Apr','vibes':['Nature','Adventure','Relaxation'],'travel':['family','adventure','wildlife'],'pitch':'Jungle, limestone peaks, and floating raft-house stays that give southern Thailand real inland range.'},
  {'name':'Langkawi','region':'Malaysia','continent':'Asia','budget':'$$','season':'Dec–Mar','vibes':['Beach','Relaxation','Family'],'travel':['family','beach','couples'],'pitch':'An easy Malaysian island pick for resort downtime, cable-car views, and low-stress tropical logistics.'},
  {'name':'Ipoh','region':'Malaysia','continent':'Asia','budget':'$','season':'Dec–Feb, Jun–Aug','vibes':['Food','Cultural','City'],'travel':['food','budget','weekend'],'pitch':'A strong short-break food city where old-town coffee culture and cave temples do more than enough.'},
  {'name':'Perhentian Islands','region':'Malaysia','continent':'Asia','budget':'$$','season':'Mar–Oct','vibes':['Beach','Relaxation','Nature'],'travel':['diving','beach','couples'],'pitch':'Clear-water, barefoot-island Malaysia at a lower-friction, lower-cost pitch than many regional rivals.'},
  {'name':'Phu Quoc','region':'Vietnam','continent':'Asia','budget':'$$','season':'Nov–Apr','vibes':['Beach','Relaxation','Family'],'travel':['family','beach','couples'],'pitch':'Vietnam’s easiest resort-island answer, with enough beach comfort to balance harder-edged city routes.'},
  {'name':'Cat Ba Island','region':'Vietnam','continent':'Asia','budget':'$','season':'Oct–Apr','vibes':['Nature','Adventure','Beach'],'travel':['budget','adventure','island-hopping'],'pitch':'The more grounded gateway to Lan Ha Bay: limestone scenery, boat trips, and fewer cruise-bubble vibes.'},
  {'name':'Vang Vieng','region':'Laos','continent':'Asia','budget':'$','season':'Nov–Feb','vibes':['Nature','Adventure','Relaxation'],'travel':['budget','adventure','backpacking'],'pitch':'Once infamous, now much more usable — karst scenery, river activities, and a classic Laos stopover.'},
  {'name':'Kampot','region':'Cambodia','continent':'Asia','budget':'$','season':'Nov–Feb','vibes':['Relaxation','Food','Unfrequented'],'travel':['budget','couples','food'],'pitch':'A river town with pepper-country day trips, mellow cafes, and one of Cambodia’s nicest slower-travel bases.'},
  {'name':'Battambang','region':'Cambodia','continent':'Asia','budget':'$','season':'Nov–Feb','vibes':['Cultural','Relaxation','Unfrequented'],'travel':['budget','history','solo'],'pitch':'A worthwhile Cambodia counterweight to Siem Reap — slower, artsier, and better for seeing everyday texture.'},
  {'name':'Baguio','region':'Philippines','continent':'Asia','budget':'$','season':'Nov–Feb','vibes':['Nature','City','Relaxation'],'travel':['budget','weekend','food'],'pitch':'The Philippines’ mountain-city escape, valued more for cooler air and local culture than postcard beaches.'},
  {'name':'Siquijor','region':'Philippines','continent':'Asia','budget':'$$','season':'Nov–May','vibes':['Beach','Relaxation','Unfrequented'],'travel':['couples','beach','offbeat'],'pitch':'Small-island Philippines with waterfalls, reef spots, and a lower-hype, higher-charm travel profile.'},
  {'name':'Camiguin','region':'Philippines','continent':'Asia','budget':'$$','season':'Nov–May','vibes':['Nature','Beach','Adventure'],'travel':['adventure','beach','offbeat'],'pitch':'Volcanoes, hot springs, and white-island sandbars in one of the country’s strongest under-the-radar bundles.'},
  {'name':'Miyajima','region':'Japan','continent':'Asia','budget':'$$','season':'Mar–May, Oct–Nov','vibes':['Cultural','Nature','Relaxation'],'travel':['history','day-trip','couples'],'pitch':'That floating torii is the hook, but deer, shrines, and a slower island rhythm keep it high-value.'},
  {'name':'Takayama','region':'Japan','continent':'Asia','budget':'$$','season':'Apr–May, Oct–Nov','vibes':['Cultural','Relaxation','Food'],'travel':['history','food','couples'],'pitch':'Old-town Japan, morning markets, and a very clean fit inside any Alps or central-Honshu circuit.'},
  {'name':'Kamakura','region':'Japan','continent':'Asia','budget':'$$','season':'Mar–May, Oct–Nov','vibes':['Cultural','Beach','Relaxation'],'travel':['day-trip','history','couples'],'pitch':'Temple-rich and seaside, with exactly the sort of easy Tokyo escape travelers keep wanting.'},
  {'name':'Naoshima','region':'Japan','continent':'Asia','budget':'$$$','season':'Apr–May, Oct–Nov','vibes':['Design','Relaxation','Nature'],'travel':['design','couples','weekend'],'pitch':'Japan’s art-island flex: museums, architecture, and a pace that feels more retreat than checklist tourism.'},
  {'name':'Beppu','region':'Japan','continent':'Asia','budget':'$$','season':'Oct–Nov, Mar–May','vibes':['Relaxation','Nature','City'],'travel':['onsen','couples','family'],'pitch':'One of Japan’s best onsen cities if your priority is soaking first and aesthetics second.'},
  {'name':'Kagoshima','region':'Japan','continent':'Asia','budget':'$$','season':'Mar–May, Oct–Nov','vibes':['Nature','City','Food'],'travel':['food','road-trip','solo'],'pitch':'A southern Japan base with Sakurajima looming nearby and much better trip-building value than its fame suggests.'},
  {'name':'Yakushima','region':'Japan','continent':'Asia','budget':'$$$','season':'Mar–May, Oct–Nov','vibes':['Nature','Hiking','Adventure'],'travel':['hiking','photography','couples'],'pitch':'Ancient cedar forests, wet green landscapes, and one of Japan’s most distinctive wilderness trips.'},
  {'name':'Kumamoto','region':'Japan','continent':'Asia','budget':'$$','season':'Mar–May, Oct–Nov','vibes':['City','Nature','Cultural'],'travel':['solo','history','road-trip'],'pitch':'A useful Kyushu anchor with a major castle, good food, and strong access to volcanic interiors.'},
  {'name':'Nagasaki','region':'Japan','continent':'Asia','budget':'$$','season':'Mar–May, Oct–Nov','vibes':['Cultural','City','Harbor'],'travel':['history','solo','food'],'pitch':'Japan’s most outward-looking historic port city, with real depth far beyond the atomic-history headline.'},
  {'name':'Kinosaki Onsen','region':'Japan','continent':'Asia','budget':'$$$','season':'Oct–Mar','vibes':['Relaxation','Romantic','Cultural'],'travel':['onsen','couples','weekend'],'pitch':'A classic ryokan-town answer for travelers who want the full yukata-and-public-baths version of Japan.'},
  {'name':'Kurashiki','region':'Japan','continent':'Asia','budget':'$$','season':'Mar–May, Oct–Nov','vibes':['Cultural','Romantic','Relaxation'],'travel':['couples','history','weekend'],'pitch':'Canals, warehouses, and a quietly handsome old district that works beautifully as a lower-key Japan stop.'},
  {'name':'Tottori','region':'Japan','continent':'Asia','budget':'$$','season':'Apr–May, Oct–Nov','vibes':['Nature','Adventure','Unfrequented'],'travel':['road-trip','offbeat','photography'],'pitch':'Famous for the dunes, but more broadly a useful off-radar slice of western Japan for scenic loops.'},
  {'name':'Otaru','region':'Japan','continent':'Asia','budget':'$$','season':'Feb–Mar, Jun–Aug','vibes':['Romantic','Harbor','Food'],'travel':['couples','food','weekend'],'pitch':'A canal city with Hokkaido seafood, glasswork shops, and enough atmosphere to justify leaving Sapporo.'},
  {'name':'Hakodate','region':'Japan','continent':'Asia','budget':'$$','season':'Apr–May, Oct–Nov','vibes':['Harbor','Food','Romantic'],'travel':['food','couples','photography'],'pitch':'Morning market seafood and one of Japan’s best night-view payoffs make this an easy Hokkaido win.'},
  {'name':'Aomori','region':'Japan','continent':'Asia','budget':'$$','season':'Apr–May, Aug, Oct–Nov','vibes':['Nature','Cultural','Food'],'travel':['road-trip','food','offbeat'],'pitch':'Apple country, Nebuta energy, and a very workable northern Honshu base for seasonal travel.'},
  {'name':'Jeonju','region':'South Korea','continent':'Asia','budget':'$$','season':'Apr–May, Sep–Oct','vibes':['Food','Cultural','City'],'travel':['food','history','couples'],'pitch':'Hanok village crowds aside, Jeonju earns its status with excellent food and one of Korea’s stronger old-core visits.'},
  {'name':'Andong','region':'South Korea','continent':'Asia','budget':'$$','season':'Apr–May, Sep–Oct','vibes':['Cultural','Relaxation','Unfrequented'],'travel':['history','couples','offbeat'],'pitch':'A heritage-heavy Korea stop that pays off for travelers who want tradition without Seoul-scale noise.'},
  {'name':'Suncheon','region':'South Korea','continent':'Asia','budget':'$$','season':'Apr–May, Sep–Oct','vibes':['Nature','Relaxation','Cultural'],'travel':['couples','outdoors','offbeat'],'pitch':'Wetlands, gardens, and easy access to slower southern Korea, useful for a trip that needs breathing room.'},
  {'name':'Gangneung','region':'South Korea','continent':'Asia','budget':'$$','season':'Jun–Aug, Sep–Oct','vibes':['Beach','Relaxation','Food'],'travel':['beach','couples','weekend'],'pitch':'An east-coast Korea favorite for coffee streets, sea views, and a cleaner beach-city profile than expected.'},
  {'name':'Tongyeong','region':'South Korea','continent':'Asia','budget':'$$','season':'Apr–May, Sep–Oct','vibes':['Harbor','Relaxation','Nature'],'travel':['couples','food','offbeat'],'pitch':'Island-dotted harbor scenery and seafood make this one of South Korea’s nicer underplayed coastal bases.'},
  {'name':'Yeosu','region':'South Korea','continent':'Asia','budget':'$$','season':'Apr–May, Sep–Oct','vibes':['Harbor','Romantic','Relaxation'],'travel':['couples','food','weekend'],'pitch':'Cable cars, bay views, and a polished waterfront setup that works particularly well for two- or three-night trips.'},
  {'name':'Yerevan','region':'Armenia','continent':'Asia','budget':'$','season':'May–Jun, Sep–Oct','vibes':['City','Cultural','Food'],'travel':['budget','solo','history'],'pitch':'Cafe-filled, pink-stone, and easy to navigate — one of the friendlier city-entry points into the Caucasus.'},
  {'name':'Belgrade','region':'Serbia','continent':'Europe','budget':'$','season':'May–Sep','vibes':['City','Nightlife','Cultural'],'travel':['budget','friends','weekend'],'pitch':'A Danube-Sava nightlife machine with enough history and food to work beyond the party reputation.'},
  {'name':'Kraków','region':'Poland','continent':'Europe','budget':'$$','season':'Apr–Jun, Sep–Oct','vibes':['Cultural','City','Romantic'],'travel':['history','couples','weekend'],'pitch':'One of Europe’s easiest city breaks to recommend: beautiful core, strong food, and serious historical depth.'},
  {'name':'Gdansk','region':'Poland','continent':'Europe','budget':'$$','season':'May–Sep','vibes':['Harbor','Cultural','City'],'travel':['weekend','history','couples'],'pitch':'A handsome Baltic city with maritime history and enough color to feel distinct from inland Poland.'},
  {'name':'Lofoten Islands','region':'Norway','continent':'Europe','budget':'$$$$','season':'Jun–Aug, Sep–Mar','vibes':['Nature','Adventure','Photography'],'travel':['photography','road-trip','outdoors'],'pitch':'Jagged peaks dropping into the sea — one of Europe’s clearest landscape flexes, especially if you drive.'},
  {'name':'Bergen','region':'Norway','continent':'Europe','budget':'$$$$','season':'May–Sep','vibes':['Harbor','Nature','City'],'travel':['outdoors','couples','weekend'],'pitch':'Norway’s prettiest city base for fjord trips, seafood, and the sort of rainy atmosphere that actually helps.'},
  {'name':'Aarhus','region':'Denmark','continent':'Europe','budget':'$$$','season':'May–Sep','vibes':['City','Design','Food'],'travel':['design','weekend','solo'],'pitch':'A smaller, easier Danish city break with enough design, dining, and waterfront polish to matter.'},
  {'name':'Gothenburg','region':'Sweden','continent':'Europe','budget':'$$$','season':'May–Sep','vibes':['City','Food','Harbor'],'travel':['food','weekend','solo'],'pitch':'A relaxed Swedish port city that’s particularly strong if your trip priorities lean seafood and neighborhoods.'},
  {'name':'Turin','region':'Piedmont','continent':'Europe','budget':'$$','season':'Apr–Jun, Sep–Nov','vibes':['City','Cultural','Food'],'travel':['food','weekend','solo'],'pitch':'Arcades, aperitivo, and easier access to Piedmont wine country than travelers often realize.'},
  {'name':'Bologna','region':'Emilia-Romagna','continent':'Europe','budget':'$$','season':'Apr–Jun, Sep–Oct','vibes':['Food','City','Cultural'],'travel':['food','weekend','solo'],'pitch':'One of Europe’s cleanest food-city wins, with arcaded streets and enough substance to last beyond a weekend.'},
  {'name':'Verona','region':'Veneto','continent':'Europe','budget':'$$','season':'Apr–Jun, Sep–Oct','vibes':['Romantic','Cultural','City'],'travel':['couples','weekend','history'],'pitch':'Yes, the Romeo and Juliet branding, but the river bends, piazzas, and scale make it genuinely pleasant.'},
  {'name':'Puglia','region':'Italy','continent':'Europe','budget':'$$','season':'May–Jun, Sep–Oct','vibes':['Beach','Food','Romantic'],'travel':['road-trip','couples','food'],'pitch':'White towns, olive groves, and a southern Italy circuit that feels sunnier and less overexposed than the usual list.'},
  {'name':'Matera','region':'Basilicata','continent':'Europe','budget':'$$$','season':'Apr–Jun, Sep–Oct','vibes':['Cultural','Romantic','Photography'],'travel':['couples','history','photography'],'pitch':'Cave dwellings and stone-city drama give Matera one of Italy’s strongest visual identities.'},
  {'name':'Lyon','region':'France','continent':'Europe','budget':'$$$','season':'Apr–Jun, Sep–Oct','vibes':['Food','City','Cultural'],'travel':['food','weekend','solo'],'pitch':'France’s smartest food-city counterweight to Paris, with riverfronts and old-town heft baked in.'},
  {'name':'Bordeaux','region':'France','continent':'Europe','budget':'$$$','season':'May–Oct','vibes':['Food','City','Romantic'],'travel':['wine','couples','weekend'],'pitch':'Elegant without being too precious, and one of Europe’s easiest bases for wine-heavy day trips.'},
  {'name':'Marseille','region':'France','continent':'Europe','budget':'$$','season':'May–Sep','vibes':['Harbor','City','Food'],'travel':['food','weekend','solo'],'pitch':'Rough-edged in a good way: a Mediterranean port city with serious character and better trip texture than its reputation.'},
  {'name':'Bilbao','region':'Basque Country','continent':'Europe','budget':'$$$','season':'May–Oct','vibes':['City','Food','Design'],'travel':['food','design','weekend'],'pitch':'A museum headline backed by a genuinely pleasant Basque city with excellent eating and easy coastal add-ons.'},
  {'name':'San Sebastián','region':'Basque Country','continent':'Europe','budget':'$$$','season':'May–Oct','vibes':['Beach','Food','Romantic'],'travel':['food','couples','luxury'],'pitch':'Pintxos, bay views, and one of Europe’s strongest food-and-beach combinations for short stays.'},
  {'name':'Granada','region':'Andalusia','continent':'Europe','budget':'$$','season':'Apr–Jun, Sep–Oct','vibes':['Cultural','Romantic','City'],'travel':['history','couples','budget'],'pitch':'The Alhambra is enough, but Granada also wins on student energy, mountain backdrop, and strong value.'},
  {'name':'Malaga','region':'Andalusia','continent':'Europe','budget':'$$','season':'Mar–Jun, Sep–Oct','vibes':['Beach','City','Food'],'travel':['weekend','food','beach'],'pitch':'An increasingly useful southern Spain base with city-beach convenience and easy Costa del Sol access.'},
  {'name':'Belfast','region':'Northern Ireland','continent':'Europe','budget':'$$','season':'May–Sep','vibes':['City','Cultural','Food'],'travel':['weekend','history','road-trip'],'pitch':'A sharper city break than many expect, especially if paired with Causeway Coast driving.'},
  {'name':'Galway','region':'Ireland','continent':'Europe','budget':'$$$','season':'May–Sep','vibes':['City','Music','Cultural'],'travel':['music','weekend','road-trip'],'pitch':'Lively pubs, west-coast access, and one of Ireland’s easiest short-stay cities to actually enjoy.'},
  {'name':'Bath','region':'England','continent':'Europe','budget':'$$$','season':'May–Sep','vibes':['Romantic','Cultural','City'],'travel':['couples','weekend','history'],'pitch':'Georgian symmetry, Roman baths, and exactly the sort of polished English short break that works.'},
  {'name':'Oxford','region':'England','continent':'Europe','budget':'$$$','season':'May–Sep','vibes':['Cultural','City','Romantic'],'travel':['history','weekend','solo'],'pitch':'Colleges, libraries, and a compact city format that makes the fantasy version of England feel unusually real.'},
  {'name':'Hamburg','region':'Germany','continent':'Europe','budget':'$$$','season':'May–Sep','vibes':['Harbor','City','Nightlife'],'travel':['weekend','friends','music'],'pitch':'A major port city with real nightlife, warehouse-district visuals, and a much cooler trip profile than first-timers expect.'},
  {'name':'Heidelberg','region':'Germany','continent':'Europe','budget':'$$$','season':'Apr–Jun, Sep–Oct','vibes':['Romantic','Cultural','City'],'travel':['couples','weekend','history'],'pitch':'Castle ruins, river views, and one of Germany’s cleaner old-town romantic setups.'},
  {'name':'Skopje','region':'North Macedonia','continent':'Europe','budget':'$','season':'Apr–Jun, Sep–Oct','vibes':['City','Cultural','Unfrequented'],'travel':['budget','weekend','offbeat'],'pitch':'Messy, idiosyncratic, and more useful as a Balkans gateway than its odd monument politics might suggest.'}
]


def main():
    data = json.loads(SOURCE.read_text())
    by_name = {row.get('name'): row for row in data if isinstance(row, dict)}
    added = 0

    for item in ADDITIONS:
        if item['name'] in by_name:
            continue
        row = {
            'name': item['name'],
            'region': item['region'],
            'continent': item['continent'],
            'photo': FALLBACK_PHOTO,
            'pitch': item['pitch'],
            'budget': item['budget'],
            'season': item['season'],
            'vibes': item['vibes'],
            'travel': item['travel'],
        }
        data.append(row)
        by_name[item['name']] = row
        added += 1

    data.sort(key=lambda r: r.get('name', '').casefold())
    SOURCE.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n')
    print(f'added={added} total={len(data)}')


if __name__ == '__main__':
    main()
