#!/usr/bin/env python3
"""Rebuild meta description / og / twitter descriptions for Mexico cities
to reference the new short titles (post title-rewrite).

The OLD descriptions were generated by truncating long titles to 4 words
("Watch for Cabo San Lucas and Cabo San Lucas Marina in Cabo San Lucas").
After the title rewrite, those truncations no longer match the new titles
and read awkwardly. This script regenerates them from the NEW titles
extracted directly from each city's HTML.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CITIES = {
    "acapulco": "Acapulco",
    "cabo-san-lucas": "Cabo San Lucas",
    "cancun": "Cancún",
    "cozumel": "Cozumel",
    "guadalajara": "Guadalajara",
    "guanajuato": "Guanajuato",
    "holbox": "Holbox",
    "isla-mujeres": "Isla Mujeres",
    "mazatlan": "Mazatlán",
    "merida": "Mérida",
    "mexico-city": "Mexico City",
    "oaxaca": "Oaxaca",
    "playa-del-carmen": "Playa del Carmen",
    "puebla": "Puebla",
    "puerto-escondido": "Puerto Escondido",
    "puerto-vallarta": "Puerto Vallarta",
    "san-cristobal-de-las-casas": "San Cristóbal de las Casas",
    "san-miguel-de-allende": "San Miguel de Allende",
    "tulum": "Tulum",
}


def extract_titles(html: str) -> list[str]:
    return [
        re.sub(r"&amp;", "&", t)
        for t in re.findall(r'<div class="scam-title">([^<]+)</div>', html)
    ]


def replace_one(html: str, attr_re: str, new_value: str) -> tuple[str, int]:
    """Replace the *content* of a meta-style attribute. Handles both
    `name="X" content="..."` and `content="..." name="X"` orderings.
    """
    count = 0

    def repl(m):
        nonlocal count
        count += 1
        return m.group(1) + new_value + m.group(3)

    html = re.sub(attr_re, repl, html)
    return html, count


def rebuild(city_slug: str, city_name: str) -> int:
    path = REPO / f"scams/{city_slug}/index.html"
    html = path.read_text()
    titles = extract_titles(html)
    if len(titles) < 2:
        return 0
    t1, t2 = titles[0], titles[1]

    desc = (
        f"Watch for {t1} and {t2} in {city_name} — 6 documented 2026 scams "
        f"with red flags and how to avoid them. Real traveler reports."
    )
    twitter_desc = (
        f"Hard-won {city_name} travel safety: {t1}, {t2}, and more. 2026 edition."
    )

    edits = 0

    # name="description"
    html, n = replace_one(
        html,
        r'(<meta name="description" content=")([^"]*)(")',
        desc,
    )
    edits += n
    # content="..." name="description"
    html, n = replace_one(
        html,
        r'(<meta content=")([^"]*)(" name="description"/?>)',
        desc,
    )
    edits += n

    # property="og:description"
    html, n = replace_one(
        html,
        r'(<meta property="og:description" content=")([^"]*)(")',
        desc,
    )
    edits += n
    html, n = replace_one(
        html,
        r'(<meta content=")([^"]*)(" property="og:description"/?>)',
        desc,
    )
    edits += n

    # name="twitter:description"
    html, n = replace_one(
        html,
        r'(<meta name="twitter:description" content=")([^"]*)(")',
        twitter_desc,
    )
    edits += n
    html, n = replace_one(
        html,
        r'(<meta content=")([^"]*)(" name="twitter:description"/?>)',
        twitter_desc,
    )
    edits += n

    # JSON-LD description: in Article object
    html, n = replace_one(
        html,
        r'("description":\s*")([^"]*)(",\s*\n?\s*"url":\s*"https://tabiji\.ai/scams/[a-z-]+/")',
        desc,
    )
    edits += n

    path.write_text(html)
    return edits


def main():
    total = 0
    for slug, name in CITIES.items():
        n = rebuild(slug, name)
        print(f"  {slug}: {n} replacements")
        total += n
    print(f"\nTotal: {total}")


if __name__ == "__main__":
    main()
