"""Per-variant manifest for /scams/everywhere/ comics.

Each entry: (page_slug, card_id, variant_slug, character, scene_md).

The variant_slug is the URL-safe identifier used as the R2 filename and
the <img> alt-text anchor. The character is one of the locked cast
members from cast.py. The scene is a 4-panel description matching the
flat-cel-shaded everywhere style.

Cast distribution across 51 variants — roughly even split:
  margie 13 · priya 12 · harry 13 · marcus 13
"""
from __future__ import annotations

# (page_slug, card_id, variant_slug, character, scene)
MANIFEST: list[tuple[str, str, str, str, str]] = [
    # ============================================================
    # AI VOICE CLONE SCAMS (5 variants)
    # ============================================================
    ("ai-voice-clone-scams", "scam-1", "family-emergency-voice-clone", "margie", (
        "Panel 1: Margie answers her cordless phone at her kitchen counter, "
        "concerned. Speech bubble (voice from phone): \"Mom, I'm in jail — I "
        "need bail money fast.\"\n"
        "Panel 2: Margie at her laptop initiating a wire transfer, the phone "
        "still pressed to her ear. Speech bubble (voice): \"Don't tell Dad — "
        "just wire it now.\"\n"
        "Panel 3: Margie pauses, sets the phone down, and dials a different "
        "number on her cell. Speech bubble (Margie): \"Wait — let me call you "
        "back on your real number.\"\n"
        "Panel 4: Margie smiles in relief, on a video call with her real son "
        "who is at home. Speech bubble (real son): \"I'm fine, Mom — that "
        "wasn't me.\""
    )),
    ("ai-voice-clone-scams", "scam-2", "reverse-grandparent-voice-clone", "priya", (
        "Panel 1: Priya at her dining table answers a call. Speech bubble "
        "(voice from phone): \"Honey, this is Grandma — I need you to wire "
        "money for the hospital.\"\n"
        "Panel 2: Priya frowns, the voice matches her grandmother's exactly. "
        "Speech bubble (voice): \"Don't tell your parents — they'll just "
        "worry.\"\n"
        "Panel 3: Priya hangs up and FaceTimes her real grandmother on her "
        "phone. Speech bubble (Priya): \"Grandma — are you in the hospital?\"\n"
        "Panel 4: Priya's real grandmother appears on screen, healthy at home "
        "with her tea. Speech bubble (real grandma): \"I'm fine, dear — "
        "someone cloned my voice.\""
    )),
    ("ai-voice-clone-scams", "scam-3", "workplace-cfo-voice-clone", "priya", (
        "Panel 1: Priya at her office desk answers her phone. Speech bubble "
        "(voice from phone): \"This is the CFO — I need you to approve a wire "
        "transfer right now.\"\n"
        "Panel 2: Priya looks at her laptop showing a wire-approval form, "
        "uncertain. Speech bubble (voice): \"Don't loop in IT — this is "
        "confidential.\"\n"
        "Panel 3: Priya walks down the hall and knocks on the real CFO's "
        "open office door. Speech bubble (Priya): \"Did you just call about a "
        "wire?\"\n"
        "Panel 4: The real CFO at her desk looks up, surprised. Speech bubble "
        "(real CFO): \"No — that wasn't me. Loop in security now.\""
    )),
    ("ai-voice-clone-scams", "scam-4", "ai-deepfake-romance-video", "harry", (
        "Panel 1: Harry on his couch on a video call with a smiling young "
        "woman on his laptop. Speech bubble (woman): \"I love seeing your "
        "face every day.\"\n"
        "Panel 2: The video call shows the woman asking for a wire transfer, "
        "Harry's expression turning concerned. Speech bubble (woman): \"My "
        "visa fee fell through — can you help?\"\n"
        "Panel 3: Harry drags the video into a reverse-image-search browser "
        "tab on his laptop. Speech bubble (Harry): \"Let me check this "
        "image.\"\n"
        "Panel 4: The reverse search shows the same face on a stock-photo site "
        "and a deepfake-detection report. Speech bubble (Harry): \"Not a real "
        "person.\""
    )),
    ("ai-voice-clone-scams", "scam-5", "silent-call-voice-harvest", "margie", (
        "Panel 1: Margie's phone rings showing UNKNOWN, she answers at her "
        "kitchen counter. Speech bubble (Margie): \"Hello? Hello?\"\n"
        "Panel 2: The line stays silent, then a faint click; Margie speaks "
        "again. Speech bubble (Margie): \"Is anyone there?\"\n"
        "Panel 3: Margie hangs up, the call log shows three unknown silent "
        "calls today. Caption box: \"Silent calls harvest your voice for "
        "later cloning.\"\n"
        "Panel 4: Margie taps the SILENCE UNKNOWN CALLERS toggle on her "
        "phone. Speech bubble (Margie): \"Unknown callers — straight to "
        "voicemail.\""
    )),
    # ============================================================
    # BANK IMPERSONATION + ZELLE (5 variants)
    # ============================================================
    ("bank-impersonation-and-zelle", "scam-1", "fake-bank-fraud-dept-safe-account", "margie", (
        "Panel 1: Margie at her kitchen counter answers her phone, alarmed. "
        "Speech bubble (voice from phone): \"This is your bank's fraud "
        "department — your account is being drained.\"\n"
        "Panel 2: Margie at her laptop with the bank's transfer form open, "
        "the voice still in her ear. Speech bubble (voice): \"Move your "
        "money to this safe account immediately.\"\n"
        "Panel 3: Margie hangs up and calls the number printed on the back of "
        "her debit card. Speech bubble (Margie): \"I'll call the number on "
        "my card.\"\n"
        "Panel 4: Real bank rep on the phone with Margie. Speech bubble "
        "(real rep): \"We didn't call you — and a real bank never asks you "
        "to move money.\""
    )),
    ("bank-impersonation-and-zelle", "scam-2", "reverse-deposit-oops-send-back", "harry", (
        "Panel 1: Harry at his kitchen table, phone in hand, sees a "
        "$3,000 deposit notification. Speech bubble (Harry): \"Where did "
        "this come from?\"\n"
        "Panel 2: Harry's phone rings; voice claims a wrong-account-number "
        "error. Speech bubble (voice): \"Sorry, that was meant for someone "
        "else — please send it back.\"\n"
        "Panel 3: Harry pauses, doesn't open Zelle. Speech bubble (Harry): "
        "\"Let me call the bank first.\"\n"
        "Panel 4: Harry on the phone with his real bank, learning the "
        "deposit was a fraudulent check that will reverse. Speech bubble "
        "(real bank rep): \"That deposit will bounce — don't send "
        "anything.\""
    )),
    ("bank-impersonation-and-zelle", "scam-3", "marketplace-seller-zelle-clawback", "priya", (
        "Panel 1: Priya at her apartment hands a buyer her old bicycle in "
        "exchange for a Zelle confirmation on his phone. Speech bubble "
        "(buyer): \"Just sent it — see?\"\n"
        "Panel 2: Three days later Priya's bank app shows the Zelle deposit "
        "reversed. Speech bubble (Priya): \"Reversed — what?\"\n"
        "Panel 3: Priya on the phone with her bank's fraud line. Speech "
        "bubble (real bank rep): \"The sender's account was compromised — "
        "Zelle has no buyer-protection clawback.\"\n"
        "Panel 4: Priya at her laptop filing a police report, an FTC "
        "complaint open in another tab. Speech bubble (Priya): \"Cash or "
        "verified bank transfer only next time.\""
    )),
    ("bank-impersonation-and-zelle", "scam-4", "authorized-but-deceived-pig-butchering", "harry", (
        "Panel 1: Harry at his kitchen table on a video call with a smiling "
        "woman, his laptop showing a crypto-trading dashboard. Speech "
        "bubble (woman): \"My uncle's signals never miss — wire just "
        "$50,000.\"\n"
        "Panel 2: Harry at his bank initiating an authorized wire transfer. "
        "The teller pauses, concerned. Speech bubble (teller): \"Sir — is "
        "someone telling you to send this?\"\n"
        "Panel 3: Harry pauses, taken aback. Speech bubble (Harry): \"It's "
        "for an investment platform online.\"\n"
        "Panel 4: The teller hands Harry an FBI pig-butchering pamphlet. "
        "Speech bubble (teller): \"Please call this number before we send "
        "anything.\""
    )),
    ("bank-impersonation-and-zelle", "scam-5", "hey-its-your-nephew-zelle", "margie", (
        "Panel 1: Margie's phone buzzes with a text from an unknown number. "
        "Speech bubble (text): \"Hey Aunt Margie, it's your nephew Tom — "
        "I lost my phone, can you Zelle me $500?\"\n"
        "Panel 2: Margie at her kitchen counter opens her Zelle app, "
        "uncertain. Speech bubble (Margie): \"Tom?\"\n"
        "Panel 3: Margie calls her real nephew Tom on his old number. Speech "
        "bubble (Margie): \"Tom — are you OK?\"\n"
        "Panel 4: Real Tom on FaceTime in his apartment, his phone fine. "
        "Speech bubble (real Tom): \"My phone is right here — that wasn't "
        "me.\""
    )),
    # ============================================================
    # CONCERT + EVENT TICKET SCAMS (3 variants)
    # ============================================================
    ("concert-and-event-ticket-scams", "scam-1", "reddit-dm-i-have-extras", "marcus", (
        "Panel 1: Marcus on his laptop scrolling Reddit DMs, a stranger "
        "offers extras. Speech bubble (DM): \"I have 2 extras for the show "
        "— Venmo F&F, $400.\"\n"
        "Panel 2: Marcus sees fake Ticketmaster confirmation screenshots in "
        "the DM. Speech bubble (DM): \"Real proof — see the screenshots?\"\n"
        "Panel 3: Marcus closes the DM and opens StubHub on his phone. "
        "Speech bubble (Marcus): \"Verified resale only.\"\n"
        "Panel 4: Marcus at the venue scanning his StubHub ticket at the "
        "gate. Speech bubble (Marcus): \"$1,000 platform fee beats $400 "
        "lost.\""
    )),
    ("concert-and-event-ticket-scams", "scam-2", "hijacked-verified-resale-account", "priya", (
        "Panel 1: Priya on her laptop browsing StubHub, sees a great-priced "
        "listing from a brand-new seller. Speech bubble (Priya): \"Way "
        "below market — too good?\"\n"
        "Panel 2: Priya hovers over the seller profile — created today, "
        "zero history. Speech bubble (Priya): \"Brand-new account.\"\n"
        "Panel 3: Priya picks a different listing from a long-tenured "
        "seller. Speech bubble (Priya): \"Established seller only.\"\n"
        "Panel 4: Priya enters the venue with a verified ticket while the "
        "first listing shows CANCELED. Speech bubble (Priya): \"Hijacked "
        "accounts get pulled before the show.\""
    )),
    ("concert-and-event-ticket-scams", "scam-3", "counterfeit-pdf-ticket-at-gate", "marcus", (
        "Panel 1: Marcus buys a PDF ticket from a Craigslist seller in a "
        "parking lot, hands over cash. Speech bubble (seller): \"Print "
        "this — section 110.\"\n"
        "Panel 2: Marcus at the venue gate, the gate scanner beeps red. "
        "Speech bubble (scanner display): \"DUPLICATE — TICKET ALREADY "
        "USED.\"\n"
        "Panel 3: Gate agent shakes her head, points to the verified-resale "
        "kiosk. Speech bubble (agent): \"This barcode was sold three times "
        "— next time use a verified platform.\"\n"
        "Panel 4: Marcus at home filing an FTC complaint with the bank "
        "fraud line on speakerphone. Speech bubble (Marcus): \"Gate scan "
        "is the only real verification.\""
    )),
    # ============================================================
    # FAKE JOB OFFERS (3 variants)
    # ============================================================
    ("fake-job-offers", "scam-1", "linkedin-fake-recruiter-dm", "priya", (
        "Panel 1: Priya at her apartment desk reads a LinkedIn DM on her "
        "laptop. Speech bubble (DM): \"Hi Priya — Senior PM role at a top "
        "fintech, $180K, fully remote.\"\n"
        "Panel 2: Priya gets an email asking for a $200 'equipment "
        "deposit.' Speech bubble (email): \"Reimbursed in your first "
        "paycheck.\"\n"
        "Panel 3: Priya searches the company's careers page directly — no "
        "such role listed. Speech bubble (Priya): \"Not on their site.\"\n"
        "Panel 4: Priya reports the recruiter's profile to LinkedIn and "
        "files an FTC complaint. Speech bubble (Priya): \"No real "
        "employer asks for money up front.\""
    )),
    ("fake-job-offers", "scam-2", "onboarding-identity-harvest", "marcus", (
        "Panel 1: Marcus on his laptop on a video interview, the "
        "interviewer in a generic backdrop. Speech bubble (interviewer): "
        "\"Welcome aboard — please fill out the W-9 link.\"\n"
        "Panel 2: The W-9 form asks for SSN, bank account, and a photo of "
        "Marcus's driver's license. Speech bubble (Marcus): \"Before any "
        "contract?\"\n"
        "Panel 3: Marcus looks up the company on the BBB and the state's "
        "business registry — no record found. Speech bubble (Marcus): "
        "\"Not a real company.\"\n"
        "Panel 4: Marcus closes the form, freezes his credit at the three "
        "bureaus on his phone. Speech bubble (Marcus): \"Credit frozen "
        "before they harvested anything.\""
    )),
    ("fake-job-offers", "scam-3", "equipment-deposit-cashiers-check", "priya", (
        "Panel 1: Priya opens her mailbox to find a cashier's check for "
        "$3,500 from her 'new employer.' Speech bubble (Priya): "
        "\"Equipment funds?\"\n"
        "Panel 2: An email instructs her to deposit the check, then Zelle "
        "$2,800 to a vendor. Speech bubble (email): \"Buy from this "
        "approved vendor — keep $700 as your bonus.\"\n"
        "Panel 3: Priya at the bank counter asks the teller about the "
        "check first. Speech bubble (teller): \"Cashier's checks can clear "
        "and then reverse — this is a fake-check scam.\"\n"
        "Panel 4: Priya tears up the check and reports the email to the "
        "FTC and FBI IC3. Speech bubble (Priya): \"Real employers don't "
        "send checks before contracts.\""
    )),
    # ============================================================
    # GIFT-CARD SCAMS (3 variants)
    # ============================================================
    ("gift-card-scams", "scam-1", "boss-impersonation-bec-gift-cards", "priya", (
        "Panel 1: Priya at her office desk reads an urgent email from "
        "'the CEO.' Speech bubble (email): \"Need 10 x $100 Amazon gift "
        "cards for a client gift — send codes ASAP.\"\n"
        "Panel 2: Priya at a Walgreens reaching for $1,000 in gift "
        "cards. She pauses to look at the email's sender domain.\n"
        "Panel 3: Priya squints at the email — the domain has an extra "
        "letter. Speech bubble (Priya): \"That's not the real domain.\"\n"
        "Panel 4: Priya at her desk calling the real CEO on his cell to "
        "verify. Speech bubble (real CEO): \"That wasn't me — forward it "
        "to security.\""
    )),
    ("gift-card-scams", "scam-2", "government-utility-gift-card-demand", "margie", (
        "Panel 1: Margie at her kitchen counter answers her phone, the "
        "voice claiming to be from the IRS. Speech bubble (voice): \"You "
        "owe back taxes — pay with Apple gift cards or face arrest.\"\n"
        "Panel 2: Margie at a drugstore reaching for $500 Apple gift "
        "cards, phone still pressed to her ear. Speech bubble (voice): "
        "\"Read me the codes immediately.\"\n"
        "Panel 3: A drugstore cashier intervenes, gesturing at the gift "
        "cards. Speech bubble (cashier): \"Ma'am — the IRS never asks for "
        "gift cards.\"\n"
        "Panel 4: Margie at home with her daughter on her laptop filing an "
        "FTC report. Speech bubble (Margie): \"No agency takes gift "
        "cards.\""
    )),
    ("gift-card-scams", "scam-3", "in-store-card-draining-sticker-overlay", "harry", (
        "Panel 1: Harry at a grocery-store gift-card rack picks a $500 "
        "Visa card off the rack to give as a birthday gift. Speech bubble "
        "(Harry): \"$500 should do it.\"\n"
        "Panel 2: Harry at home hands the card to his grandkid who scans "
        "the barcode at checkout — DECLINED. Speech bubble (cashier "
        "display): \"BALANCE: $0.\"\n"
        "Panel 3: Harry inspects the card under a lamp — the barcode "
        "sticker peels off, revealing a different barcode underneath. "
        "Speech bubble (Harry): \"Sticker overlay.\"\n"
        "Panel 4: Harry at a different store, picking a card from "
        "BEHIND the rack instead of the front. Speech bubble (Harry): "
        "\"Always pull from behind the front row.\""
    )),
    # ============================================================
    # MARKETPLACE SCAMS — FB / CRAIGSLIST (4 variants)
    # ============================================================
    ("marketplace-scams-fb-craigslist", "scam-1", "fake-listing-non-delivery", "priya", (
        "Panel 1: Priya on her laptop browsing Facebook Marketplace, sees a "
        "$200 PS5 listing with stock-photo images. Speech bubble (Priya): "
        "\"Way below market.\"\n"
        "Panel 2: Priya messages the seller; the seller demands Zelle "
        "before any meetup. Speech bubble (seller): \"Zelle me first, then "
        "I'll arrange shipping.\"\n"
        "Panel 3: Priya does a reverse-image search — the listing photo is "
        "from a different seller's eBay listing. Speech bubble (Priya): "
        "\"Stolen photo.\"\n"
        "Panel 4: Priya reports the listing to Facebook and finds a real "
        "local seller for in-person cash pickup. Speech bubble (Priya): "
        "\"Cash, in-person, daylight, public spot.\""
    )),
    ("marketplace-scams-fb-craigslist", "scam-2", "google-voice-6-digit-hijack", "marcus", (
        "Panel 1: Marcus on his phone listing a guitar on Craigslist, gets "
        "a buyer message. Speech bubble (buyer): \"Want to verify you're "
        "real — I'll send a 6-digit code, just text it back.\"\n"
        "Panel 2: Marcus's phone shows a Google Voice verification text. "
        "Speech bubble (Marcus): \"Why does buying a guitar need a "
        "code?\"\n"
        "Panel 3: Marcus searches 'Google Voice 6-digit code scam' on his "
        "laptop. Speech bubble (search result): \"Scammer hijacks your "
        "phone number to register Google Voice.\"\n"
        "Panel 4: Marcus blocks the buyer and never sends the code. Speech "
        "bubble (Marcus): \"Never share verification codes.\""
    )),
    ("marketplace-scams-fb-craigslist", "scam-3", "compromised-payment-clawback", "priya", (
        "Panel 1: Priya hands a buyer her bicycle in a coffee-shop parking "
        "lot, watching the Zelle confirmation appear on the buyer's phone. "
        "Speech bubble (buyer): \"Sent — see?\"\n"
        "Panel 2: Five days later Priya's bank app shows the Zelle "
        "reversed: \"Sender's account closed — funds returned.\" Speech "
        "bubble (Priya): \"Reversed?\"\n"
        "Panel 3: Priya on the phone with her bank's fraud line. Speech "
        "bubble (real bank rep): \"That sender used a stolen account — "
        "Zelle has no clawback protection.\"\n"
        "Panel 4: Priya updates her listings: 'CASH ONLY, IN-PERSON, "
        "DAYLIGHT.' Speech bubble (Priya): \"Bills first, then bicycle.\""
    )),
    ("marketplace-scams-fb-craigslist", "scam-4", "rental-scam-fake-apartment", "marcus", (
        "Panel 1: Marcus on his laptop browsing Facebook apartment "
        "listings, sees a $1,200/mo studio in a $2,500/mo neighborhood. "
        "Speech bubble (Marcus): \"This price is wrong.\"\n"
        "Panel 2: The 'landlord' messages: pay first month + deposit via "
        "Zelle to 'hold' the unit, no in-person tour. Speech bubble "
        "(landlord): \"I'm overseas — Zelle the deposit and I'll mail you "
        "keys.\"\n"
        "Panel 3: Marcus reverse-image-searches the photo — same "
        "apartment posted by the real landlord on Apartments.com at the "
        "actual market rate. Speech bubble (Marcus): \"Stolen listing "
        "photo.\"\n"
        "Panel 4: Marcus reports the fake to Facebook and books a real "
        "in-person tour. Speech bubble (Marcus): \"No tour, no rent — "
        "ever.\""
    )),
    # ============================================================
    # MEDICARE + ELDER SCAMS (6 variants)
    # ============================================================
    ("medicare-and-elder-scams", "scam-1", "new-plastic-medicare-card", "margie", (
        "Panel 1: Margie at her kitchen counter answers her phone. Speech "
        "bubble (voice from phone): \"Medicare is issuing new plastic "
        "cards — verify your number to receive yours.\"\n"
        "Panel 2: The voice asks for her full Medicare number, SSN, and "
        "bank account. Speech bubble (Margie): \"That's a lot of "
        "information.\"\n"
        "Panel 3: Margie hangs up and calls 1-800-MEDICARE on her phone. "
        "Speech bubble (real Medicare rep): \"We never call to ask for "
        "your number — your card is paper, not plastic.\"\n"
        "Panel 4: Margie reports the call to Senior Medicare Patrol on "
        "her laptop. Speech bubble (Margie): \"Medicare doesn't cold-call "
        "anyone.\""
    )),
    ("medicare-and-elder-scams", "scam-2", "catheter-dme-billing-fraud", "harry", (
        "Panel 1: Harry opens a package in his mailbox — unsolicited "
        "catheters and a leg brace he never ordered. Speech bubble "
        "(Harry): \"I didn't order any of this.\"\n"
        "Panel 2: Harry checks his Medicare Summary Notice on his laptop "
        "— $4,200 billed for DME he never received. Speech bubble "
        "(Harry): \"Billed in my name.\"\n"
        "Panel 3: Harry on the phone with Senior Medicare Patrol, "
        "documenting the fraud. Speech bubble (real SMP rep): \"This is "
        "the catheter-billing scheme — we'll file the fraud report.\"\n"
        "Panel 4: Harry returns the unopened box and shreds his old "
        "Medicare statements. Speech bubble (Harry): \"Always check the "
        "Summary Notice.\""
    )),
    ("medicare-and-elder-scams", "scam-3", "medicare-advantage-open-enrollment-pressure", "margie", (
        "Panel 1: Margie at her kitchen counter answers her phone. Speech "
        "bubble (voice from phone): \"Your Medicare plan is changing — "
        "switch today or lose coverage.\"\n"
        "Panel 2: The voice pressures Margie to give her plan ID and "
        "credit card. Speech bubble (voice): \"Just confirm your details "
        "and I'll switch you now.\"\n"
        "Panel 3: Margie hangs up and calls her real plan's customer "
        "service. Speech bubble (real plan rep): \"No agent calls you "
        "first — that was an unsolicited contact, which is illegal.\"\n"
        "Panel 4: Margie reports the call to her State Health Insurance "
        "Assistance Program. Speech bubble (Margie): \"Real Medicare "
        "agents wait for me to call them.\""
    )),
    ("medicare-and-elder-scams", "scam-4", "utility-shutoff-fear-call", "harry", (
        "Panel 1: Harry at his kitchen table answers his phone. Speech "
        "bubble (voice from phone): \"This is the power company — your "
        "service shuts off in 30 minutes if you don't pay.\"\n"
        "Panel 2: The voice demands payment via prepaid debit card. "
        "Speech bubble (voice): \"Buy a $300 card and read me the "
        "number.\"\n"
        "Panel 3: Harry hangs up and calls his utility's customer-service "
        "number from his last paper bill. Speech bubble (real utility "
        "rep): \"Your account is current — we never demand prepaid "
        "cards.\"\n"
        "Panel 4: Harry reports the spoofed call to his utility's fraud "
        "line. Speech bubble (Harry): \"Real utilities mail letters — "
        "they don't threaten 30-minute shutoffs.\""
    )),
    ("medicare-and-elder-scams", "scam-5", "fake-jury-duty-sheriff-call", "margie", (
        "Panel 1: Margie at her kitchen counter answers her phone, the "
        "voice claiming to be a sheriff. Speech bubble (voice): \"You "
        "missed jury duty — there's a warrant for your arrest.\"\n"
        "Panel 2: The voice demands a 'bond payment' via gift card or "
        "wire transfer. Speech bubble (voice): \"Buy $1,500 in cards or "
        "we'll send a deputy.\"\n"
        "Panel 3: Margie hangs up and calls her county courthouse "
        "directly. Speech bubble (real court clerk): \"No warrant — and "
        "no court ever takes gift cards.\"\n"
        "Panel 4: Margie reports the call to the FTC and her state AG "
        "consumer-protection line. Speech bubble (Margie): \"Real "
        "courts use mail, not phones.\""
    )),
    ("medicare-and-elder-scams", "scam-6", "fake-arrest-warrant-mailer", "harry", (
        "Panel 1: Harry at his mailbox holds an official-looking arrest-"
        "warrant letter. Speech bubble (letter): \"WARRANT — call this "
        "number within 24 hours to clear.\"\n"
        "Panel 2: Harry at his kitchen table calls the listed number, the "
        "voice demands $2,800 in gift cards. Speech bubble (voice): "
        "\"Pay now or face arrest.\"\n"
        "Panel 3: Harry hangs up and calls the real court clerk in the "
        "jurisdiction shown on the letter. Speech bubble (real clerk): "
        "\"No such warrant — that's a known scam mailer.\"\n"
        "Panel 4: Harry shreds the letter and files an FTC complaint on "
        "his laptop. Speech bubble (Harry): \"Real warrants come from a "
        "real court, never with a payment hotline.\""
    )),
    # ============================================================
    # PACKAGE-TEXT SCAMS (3 variants)
    # ============================================================
    ("package-text-scams", "scam-1", "usps-redelivery-fee-text", "priya", (
        "Panel 1: Priya on her phone gets a USPS-looking text. Speech "
        "bubble (text): \"Package held for $1.95 redelivery fee — click "
        "to pay.\"\n"
        "Panel 2: Priya pauses, the link is 'usps-redelivery.com' (not a "
        ".gov). Speech bubble (Priya): \"Not a real USPS domain.\"\n"
        "Panel 3: Priya opens the real USPS Informed Delivery app — no "
        "package held. Speech bubble (app): \"No outstanding packages.\"\n"
        "Panel 4: Priya reports the text to 7726 (SPAM) and deletes it. "
        "Speech bubble (Priya): \"USPS uses .gov, never charges $1.95 "
        "fees.\""
    )),
    ("package-text-scams", "scam-2", "fedex-ups-amazon-carrier-clones", "marcus", (
        "Panel 1: Marcus on his phone gets a FedEx-branded text with a "
        "tracking-failure notice. Speech bubble (text): \"FedEx — your "
        "package failed delivery, click to reschedule.\"\n"
        "Panel 2: The link looks like 'fedx-update.net' — Marcus zooms in, "
        "spots the misspelling. Speech bubble (Marcus): \"Missing an E.\"\n"
        "Panel 3: Marcus on the FedEx website (typed manually) checks "
        "tracking — no package in transit. Speech bubble (FedEx site): "
        "\"No packages found.\"\n"
        "Panel 4: Marcus forwards the text to FedEx's abuse address and "
        "reports to 7726. Speech bubble (Marcus): \"Always type the real "
        "domain — never click texted links.\""
    )),
    ("package-text-scams", "scam-3", "address-verification-identity-harvest", "priya", (
        "Panel 1: Priya gets a text claiming Amazon needs to verify her "
        "address. Speech bubble (text): \"Your package can't be "
        "delivered — verify address and last 4 of card.\"\n"
        "Panel 2: The link asks for full name, address, DOB, and last 4 "
        "of credit card. Speech bubble (Priya): \"They never need a card "
        "for an address.\"\n"
        "Panel 3: Priya logs into Amazon directly — no delivery problem "
        "anywhere. Speech bubble (Amazon site): \"All shipments on "
        "schedule.\"\n"
        "Panel 4: Priya reports the link to Amazon's 'stop-spoofing' page "
        "and 7726. Speech bubble (Priya): \"Amazon never asks for card "
        "details over text.\""
    )),
    # ============================================================
    # PIG-BUTCHERING (7 variants)
    # ============================================================
    ("pig-butchering", "scam-1", "hinge-bumble-uncles-trading-signals", "priya", (
        "Panel 1: Priya on her couch swiping Hinge, matches with a "
        "smiling man named 'Daniel.' Speech bubble (chat): \"You're "
        "stunning — let's move to WhatsApp.\"\n"
        "Panel 2: Three weeks later on WhatsApp, Daniel pitches his "
        "uncle's trading platform. Speech bubble (Daniel): \"My uncle's "
        "signals never miss — let me show you.\"\n"
        "Panel 3: Priya searches 'Daniel Lin trader' on her laptop — same "
        "photo on a known pig-butchering scam site. Speech bubble "
        "(Priya): \"Stock photo from a scam database.\"\n"
        "Panel 4: Priya unmatches, blocks, and reports to Hinge + FBI "
        "IC3. Speech bubble (Priya): \"Investment pitches off dating "
        "apps — always a scam.\""
    )),
    ("pig-butchering", "scam-2", "wrong-number-text-crypto-pitch", "harry", (
        "Panel 1: Harry at his kitchen table gets a 'wrong number' text. "
        "Speech bubble (text): \"Hi Linda, dinner Friday at 7?\"\n"
        "Panel 2: Harry replies 'wrong number' — the sender chats back, "
        "two weeks later mentions her crypto trading. Speech bubble "
        "(text): \"My uncle's platform is amazing.\"\n"
        "Panel 3: Harry searches the platform name — known pig-butchering "
        "shell on the FBI IC3 advisory list. Speech bubble (Harry): "
        "\"Pig-butchering script.\"\n"
        "Panel 4: Harry blocks the number, reports to FBI IC3. Speech "
        "bubble (Harry): \"No 'wrong number' leads to a real "
        "friendship.\""
    )),
    ("pig-butchering", "scam-3", "linkedin-mentor-trading-class", "marcus", (
        "Panel 1: Marcus at his desk gets a LinkedIn DM from a 'mentor' "
        "offering a side-hustle trading group. Speech bubble (DM): \"Join "
        "my private trading class — first week free.\"\n"
        "Panel 2: The Telegram group adds him; signals + screenshots show "
        "huge gains. Speech bubble (group admin): \"Deposit $5K to start "
        "— withdraw anytime.\"\n"
        "Panel 3: Marcus checks the trading platform's domain on the FBI "
        "IC3 advisory list — flagged as pig-butchering. Speech bubble "
        "(Marcus): \"On the IC3 list.\"\n"
        "Panel 4: Marcus leaves the group, reports the LinkedIn account, "
        "files an IC3 complaint. Speech bubble (Marcus): \"Real mentors "
        "don't pitch deposits.\""
    )),
    ("pig-butchering", "scam-4", "withdrawal-tax-trap", "harry", (
        "Panel 1: Harry on his laptop sees a $200,000 'profit' on a "
        "trading-platform dashboard. Speech bubble (Harry): \"Time to "
        "cash out.\"\n"
        "Panel 2: A withdrawal request triggers a pop-up: '20% withdrawal "
        "tax due — wire $40,000 to release funds.' Speech bubble (popup): "
        "\"Tax payment required.\"\n"
        "Panel 3: Harry pauses, searches 'withdrawal tax crypto' — top "
        "result is the IC3 pig-butchering advisory. Speech bubble "
        "(Harry): \"That tax is fake.\"\n"
        "Panel 4: Harry on the phone with the FBI IC3 hotline, the "
        "platform locked on his laptop. Speech bubble (Harry): \"No real "
        "platform charges a withdrawal tax.\""
    )),
    ("pig-butchering", "scam-5", "telegram-liquidity-yield-farming", "marcus", (
        "Panel 1: Marcus on his phone in a Telegram channel watches a "
        "'liquidity provider' pitch. Speech bubble (admin): \"Stake your "
        "USDT — 8% daily yield, fully audited.\"\n"
        "Panel 2: Marcus's wallet shows a small test deposit returning "
        "the promised yield, then a banner urges scaling up. Speech "
        "bubble (admin): \"Whale tier opens at $50K.\"\n"
        "Panel 3: Marcus pulls up DeFiLlama and the smart contract — no "
        "audit, owner-controlled. Speech bubble (Marcus): \"No real "
        "audit. Owner can drain it.\"\n"
        "Panel 4: Marcus withdraws the test deposit and posts the "
        "contract address to a public scam-tracker. Speech bubble "
        "(Marcus): \"If the smart contract isn't audited, it's a "
        "rug.\""
    )),
    ("pig-butchering", "scam-6", "spouse-doesnt-know-secret-account", "harry", (
        "Panel 1: Harry at his kitchen table on his laptop, the trading "
        "dashboard hidden behind a different tab. Speech bubble (chat): "
        "\"Don't tell your wife — she'll just worry.\"\n"
        "Panel 2: Harry has wired $80,000 from a hidden account; his "
        "wife is in another room. Caption box: \"The 'secret' framing IS "
        "the scam.\"\n"
        "Panel 3: Harry pauses, closes his laptop, walks into the living "
        "room and sits down with his wife. Speech bubble (Harry): \"I "
        "need to tell you something.\"\n"
        "Panel 4: Harry and his wife together at the kitchen table on "
        "the FBI IC3 victim hotline. Speech bubble (Harry): \"Secrecy is "
        "the diagnostic — every time.\""
    )),
    ("pig-butchering", "scam-7", "recovery-scam-after-public-victim-post", "priya", (
        "Panel 1: Priya at her laptop posts an r/Scams victim story. "
        "Within an hour, three DMs arrive offering 'fund recovery.' "
        "Speech bubble (DM): \"I can recover your funds — 15% upfront "
        "fee.\"\n"
        "Panel 2: Priya reads the next DM, identical wording from a "
        "different account. Speech bubble (Priya): \"Same script.\"\n"
        "Panel 3: Priya screenshots the DMs and posts them to the same "
        "thread as a warning. Speech bubble (post): \"Recovery DMs are "
        "the parasite layer — block them all.\"\n"
        "Panel 4: Priya reports each account to Reddit + IC3, blocks "
        "every recovery DM. Speech bubble (Priya): \"Real recovery is "
        "free — through the FBI, not DMs.\""
    )),
    # ============================================================
    # REAL-ESTATE WIRE FRAUD (3 variants)
    # ============================================================
    ("real-estate-wire-fraud", "scam-1", "last-minute-wire-instruction-swap", "priya", (
        "Panel 1: Priya at her kitchen table reads an email from her "
        "title company on closing day. Speech bubble (email): \"Updated "
        "wire instructions — please use the new account.\"\n"
        "Panel 2: Priya at her bank with the wire form open, the teller "
        "ready to send $300,000. Speech bubble (Priya): \"Wait — let me "
        "verify first.\"\n"
        "Panel 3: Priya calls the title company on the number from her "
        "original signed contract. Speech bubble (real title agent): "
        "\"We didn't send any new instructions — that's a fraud "
        "email.\"\n"
        "Panel 4: Priya wires to the original account and forwards the "
        "fraud email to the title company's IT. Speech bubble (Priya): "
        "\"Always verify on the original number.\""
    )),
    ("real-estate-wire-fraud", "scam-2", "email-editing-mitm", "marcus", (
        "Panel 1: Marcus at his laptop sees an email thread with his "
        "real-estate agent — the account number is different from "
        "yesterday's email. Speech bubble (Marcus): \"This account "
        "changed.\"\n"
        "Panel 2: Marcus's mailbox shows two near-identical 'agent' "
        "emails — one with one extra letter in the domain. Speech bubble "
        "(Marcus): \"Lookalike domain.\"\n"
        "Panel 3: Marcus calls his agent on her cell from his phone "
        "contacts. Speech bubble (real agent): \"My account hasn't "
        "changed — your inbox is being intercepted.\"\n"
        "Panel 4: Marcus on a fresh email account, his old inbox "
        "quarantined, IT working on it. Speech bubble (Marcus): \"Always "
        "verify wire details by phone, never by email reply.\""
    )),
    ("real-estate-wire-fraud", "scam-3", "spoofed-callback-number", "priya", (
        "Panel 1: Priya at her kitchen table calls the 'verify' phone "
        "number printed in the wire-instruction email. Speech bubble "
        "(voice): \"Yes, the new instructions are correct.\"\n"
        "Panel 2: The voice confirms everything — but the number was "
        "spoofed by the same scammer. Caption box: \"Email-listed numbers "
        "can be spoofed.\"\n"
        "Panel 3: Priya hangs up, opens her ORIGINAL signed contract, "
        "and dials the title company's number from page one. Speech "
        "bubble (Priya): \"Use the original document number.\"\n"
        "Panel 4: Priya on the phone with the real title company — fraud "
        "confirmed, original instructions intact. Speech bubble (real "
        "agent): \"Always call the number you had before this email.\""
    )),
    # ============================================================
    # RECOVERY SCAMS (4 variants)
    # ============================================================
    ("recovery-scams", "scam-1", "fund-recovery-specialist-dm", "margie", (
        "Panel 1: Margie at her laptop posts an r/Scams story about "
        "losing $5,000 to a tech-support scam. Within an hour, a DM "
        "arrives. Speech bubble (DM): \"I can recover your funds — 15% "
        "upfront fee.\"\n"
        "Panel 2: The 'specialist' asks for a $750 retainer via "
        "cryptocurrency. Speech bubble (DM): \"Send the retainer to this "
        "wallet to start.\"\n"
        "Panel 3: Margie googles the specialist's name + 'scam' — same "
        "name on the FBI IC3 advisory and r/Scams warning post. Speech "
        "bubble (Margie): \"Recovery scammer.\"\n"
        "Panel 4: Margie blocks the DM and reports to Reddit + IC3. "
        "Speech bubble (Margie): \"Real recovery is free, through the "
        "FBI.\""
    )),
    ("recovery-scams", "scam-2", "blockchain-forensic-crypto-recovery", "marcus", (
        "Panel 1: Marcus at his laptop reads an email from a "
        "'blockchain forensic firm.' Speech bubble (email): \"We can "
        "trace and recover your stolen crypto for a 20% fee.\"\n"
        "Panel 2: The firm asks for $2,500 in advance + Marcus's wallet "
        "private key. Speech bubble (email): \"Send your seed phrase to "
        "begin the trace.\"\n"
        "Panel 3: Marcus checks the firm's name on the SEC + state AG "
        "advisories — flagged as fraudulent. Speech bubble (Marcus): "
        "\"Real forensic firms never ask for your seed phrase.\"\n"
        "Panel 4: Marcus reports the email to FBI IC3 and the SEC. "
        "Speech bubble (Marcus): \"Anyone asking for a seed phrase is "
        "the second scam.\""
    )),
    ("recovery-scams", "scam-3", "fake-law-firm-asset-recovery", "harry", (
        "Panel 1: Harry at his kitchen table reads an unsolicited "
        "letter on letterhead from 'Asset Recovery Counsel.' Speech "
        "bubble (letter): \"We've located your stolen funds — call our "
        "office to claim them.\"\n"
        "Panel 2: A voice on the office line asks for a $3,500 "
        "'court-filing fee' wired to an escrow account. Speech bubble "
        "(voice): \"Standard court fee — refundable on settlement.\"\n"
        "Panel 3: Harry searches the firm on his state bar's "
        "attorney-search tool — no record. Speech bubble (Harry): \"No "
        "such firm.\"\n"
        "Panel 4: Harry forwards the letter to his state bar's consumer "
        "fraud line and the FTC. Speech bubble (Harry): \"Real lawyers "
        "are listed on the state bar.\""
    )),
    ("recovery-scams", "scam-4", "government-recovered-funds-release-fee", "margie", (
        "Panel 1: Margie at her kitchen counter answers her phone, the "
        "voice claiming to be from the FTC. Speech bubble (voice): \"We "
        "recovered your scam funds — pay the $1,200 release fee.\"\n"
        "Panel 2: The voice demands a wire transfer or gift card to "
        "release the funds. Speech bubble (voice): \"Wire the fee — "
        "funds release in 24 hours.\"\n"
        "Panel 3: Margie hangs up and calls the real FTC at "
        "1-877-FTC-HELP. Speech bubble (real FTC rep): \"We never call "
        "you, and we never charge a release fee.\"\n"
        "Panel 4: Margie reports the call to the FTC and her state AG. "
        "Speech bubble (Margie): \"No agency takes fees to release "
        "money.\""
    )),
    # ============================================================
    # TECH-SUPPORT SCAMS (5 variants)
    # ============================================================
    ("tech-support-scams", "scam-1", "browser-popup-windows-locked", "margie", (
        "Panel 1: Margie at her laptop sees a full-screen red Windows-"
        "branded popup with a phone number. Speech bubble (popup): "
        "\"WINDOWS LOCKED — call 1-800-XXX-XXXX immediately.\"\n"
        "Panel 2: Margie reaches for her phone, then pauses. Caption "
        "box: \"No real OS asks you to call a phone number.\"\n"
        "Panel 3: Margie holds the laptop power button to force shutdown, "
        "doesn't dial. Speech bubble (Margie): \"Just turn it off.\"\n"
        "Panel 4: Margie reboots, runs an antivirus scan, the popup "
        "gone. Speech bubble (Margie): \"Real Microsoft never displays a "
        "phone number.\""
    )),
    ("tech-support-scams", "scam-2", "geek-squad-norton-renewal-email", "harry", (
        "Panel 1: Harry at his kitchen table reads an email from 'Geek "
        "Squad' about a $499 auto-renewal. Speech bubble (email): "
        "\"Charge processed — call to dispute.\"\n"
        "Panel 2: The phone agent asks for remote access to 'process the "
        "refund.' Speech bubble (voice): \"Install AnyDesk so I can "
        "refund you.\"\n"
        "Panel 3: Harry hangs up and logs into his actual Best Buy "
        "account — no charge, no subscription. Speech bubble (Harry): "
        "\"No charge anywhere.\"\n"
        "Panel 4: Harry reports the email to Geek Squad's abuse address "
        "and deletes it. Speech bubble (Harry): \"Real refunds never "
        "need remote access.\""
    )),
    ("tech-support-scams", "scam-3", "seo-poisoned-microsoft-support", "margie", (
        "Panel 1: Margie at her laptop searches 'Microsoft support phone' "
        "and clicks the top result. Speech bubble (search result): "
        "\"Microsoft 24/7 Help — 1-800-XXX-XXXX.\"\n"
        "Panel 2: A voice on the line asks Margie to install "
        "ConnectWise to 'verify her account.' Speech bubble (voice): "
        "\"Install this app so I can check your computer.\"\n"
        "Panel 3: Margie pauses, types support.microsoft.com directly "
        "into her browser. Speech bubble (Margie): \"Type the real "
        "domain.\"\n"
        "Panel 4: Margie on Microsoft's actual support chat, the "
        "scammer's call dropped. Speech bubble (real Microsoft agent): "
        "\"Microsoft support never calls you, and we never need remote "
        "access.\""
    )),
    ("tech-support-scams", "scam-4", "remote-access-installation", "harry", (
        "Panel 1: Harry on the phone at his kitchen table, the voice "
        "guiding him to install AnyDesk on his laptop. Speech bubble "
        "(voice): \"Type 'AnyDesk' and install it now.\"\n"
        "Panel 2: Harry's screen shows the AnyDesk download page, his "
        "cursor hovering over INSTALL. Speech bubble (Harry): \"Why do "
        "they need to see my screen?\"\n"
        "Panel 3: Harry hangs up, closes the browser tab, doesn't "
        "install. Speech bubble (Harry): \"Never install for a "
        "stranger.\"\n"
        "Panel 4: Harry on a video call with his real bank's fraud "
        "line. Speech bubble (real bank rep): \"AnyDesk + a stranger = "
        "always a scam.\""
    )),
    ("tech-support-scams", "scam-5", "bank-drain-via-remote-controlled-browser", "margie", (
        "Panel 1: Margie at her laptop, the scammer remote-controlling "
        "her browser to log into her bank. Speech bubble (voice): \"Just "
        "let me verify the balance.\"\n"
        "Panel 2: The cursor moves on its own, drafting a $9,800 "
        "outbound transfer. Speech bubble (Margie): \"Why is it making "
        "transfers?\"\n"
        "Panel 3: Margie unplugs her laptop power and Wi-Fi, terminating "
        "the session. Speech bubble (Margie): \"Off — now.\"\n"
        "Panel 4: Margie at her bank in person, the teller freezing the "
        "account. Speech bubble (real teller): \"You stopped it — we'll "
        "reverse the transfer.\""
    )),
    # ============================================================
    # DOOR-TO-DOOR CONTRACTOR SCAMS (5 variants)
    # ============================================================
    ("door-to-door-contractor-scams", "scam-1", "storm-chaser-roofing-deductible-waiver", "harry", (
        "Panel 1: Harry at his front door talks to a contractor with a "
        "clipboard and out-of-state-plates truck visible behind him. "
        "Speech bubble (contractor): \"We saw storm damage on your roof "
        "— we can absorb your $1,000 deductible.\"\n"
        "Panel 2: The contractor on Harry's roof points a phone camera "
        "at shingles. Speech bubble (contractor): \"Sign the Assignment "
        "of Benefits today — 48-hour insurance window.\"\n"
        "Panel 3: Harry at his kitchen table calls his real insurance "
        "carrier, the contractor's clipboard untouched. Speech bubble "
        "(real carrier): \"Deductible waivers are illegal — we'll send "
        "our own inspector.\"\n"
        "Panel 4: Harry hands the contractor's card to a state-insurance-"
        "commissioner intake clerk. Speech bubble (Harry): \"Real local "
        "contractors wait three days.\""
    )),
    ("door-to-door-contractor-scams", "scam-2", "asphalt-leftover-materials-driveway", "margie", (
        "Panel 1: Margie at her front door speaks with a paving-truck "
        "salesman on her walkway. Speech bubble (salesman): \"We just "
        "finished a job down the road — leftover sealant, half price "
        "today.\"\n"
        "Panel 2: The salesman points to her driveway and demands "
        "$1,200 cash up front. Speech bubble (salesman): \"Cash only — "
        "lock in materials now.\"\n"
        "Panel 3: Margie on her phone looking up the LLC name on her "
        "state contractor-licensing board. Speech bubble (website): "
        "\"NO LICENSE FOUND.\"\n"
        "Panel 4: Margie closes the door and files a BBB Scam Tracker "
        "report on her laptop. Speech bubble (Margie): \"Real driveway "
        "contractors send written estimates first.\""
    )),
    ("door-to-door-contractor-scams", "scam-3", "post-storm-tree-work-cash-up-front", "harry", (
        "Panel 1: Harry at his front door speaks with a tree-crew lead "
        "after a windstorm. Speech bubble (crew lead): \"That limb's "
        "about to drop — $1,500 cash, two hours.\"\n"
        "Panel 2: Harry asks for the crew's general-liability insurance "
        "certificate; the crew lead hesitates. Speech bubble (Harry): "
        "\"Can I see your insurance certificate?\"\n"
        "Panel 3: Harry on the phone with his real homeowner's insurance "
        "carrier instead. Speech bubble (real carrier): \"We cover "
        "hazard-tree removal — we'll dispatch a vetted ISA arborist.\"\n"
        "Panel 4: A real ISA-certified arborist removes the limb safely "
        "from Harry's roof. Speech bubble (Harry): \"Insurance + ISA "
        "credential beats cash discount every time.\""
    )),
    ("door-to-door-contractor-scams", "scam-4", "fake-inspection-pretext-entry", "margie", (
        "Panel 1: Margie at her front door speaks with a man in a polo "
        "shirt with an embroidered patch holding a clipboard. Speech "
        "bubble (man): \"Utility flagged your address — emergency gas-"
        "line inspection.\"\n"
        "Panel 2: The man asks to enter the home; Margie pauses, hand "
        "on the door. Speech bubble (Margie): \"Let me call the utility "
        "first.\"\n"
        "Panel 3: Margie at her kitchen table calls the customer-service "
        "number from her last utility bill. Speech bubble (real utility "
        "rep): \"We never canvass door-to-door — that's a scam.\"\n"
        "Panel 4: Margie reports the visit to her utility's fraud line "
        "and her state AG. Speech bubble (Margie): \"Real utilities call "
        "first; they don't show up.\""
    )),
    ("door-to-door-contractor-scams", "scam-5", "door-to-door-solar-utility-program", "priya", (
        "Panel 1: Priya at her front door speaks with a solar canvasser "
        "in a polo with an embroidered government-looking patch. Speech "
        "bubble (canvasser): \"You qualify for a state energy program — "
        "no upfront cost, sign today.\"\n"
        "Panel 2: The canvasser holds out a tablet with a 25-year power-"
        "purchase agreement loaded. Speech bubble (canvasser): \"Just "
        "sign here on the tablet.\"\n"
        "Panel 3: Priya searches the company name and the claimed "
        "program on her laptop — no record at the state energy office. "
        "Speech bubble (state-website): \"No such program.\"\n"
        "Panel 4: Priya files a state-AG report and books three "
        "independent solar quotes. Speech bubble (Priya): \"25-year "
        "contracts deserve more than thirty seconds.\""
    )),
    # ============================================================
    # PHONE-IMPERSONATION GOVERNMENT SCAMS (5 variants)
    # ============================================================
    ("phone-impersonation-government", "scam-1", "ssa-number-suspended-robocall", "margie", (
        "Panel 1: Margie at her kitchen counter answers her landline. "
        "Speech bubble (recorded voice): \"This is the Social Security "
        "Administration — your number has been suspended.\"\n"
        "Panel 2: Margie listens as the recording instructs her to press "
        "1; her finger hovers over the keypad. Speech bubble (recording): "
        "\"Press 1 to speak with an investigating agent.\"\n"
        "Panel 3: Margie hangs up and calls 1-800-772-1213 (the SSA's "
        "real published number) on her phone. Speech bubble (real SSA "
        "rep): \"SSA never suspends Social Security numbers.\"\n"
        "Panel 4: Margie files a report at oig.ssa.gov on her laptop. "
        "Speech bubble (Margie): \"SSN can't be suspended — that's the "
        "diagnostic.\""
    )),
    ("phone-impersonation-government", "scam-2", "irs-tax-debt-arrest-threat", "harry", (
        "Panel 1: Harry at his desk answers his cell phone; the caller-"
        "ID display reads '1-800-829-1040'. Speech bubble (voice): "
        "\"This is Special Agent Matthews — IRS warrant for $7,200 "
        "unpaid taxes.\"\n"
        "Panel 2: The voice tells Harry to drive to a Walmart and buy "
        "$7,200 in prepaid debit cards. Speech bubble (voice): \"Stay on "
        "the line until you read me the codes.\"\n"
        "Panel 3: Harry hangs up and logs into his real IRS account on "
        "his laptop. Speech bubble (IRS website): \"BALANCE OWED: $0.\"\n"
        "Panel 4: Harry files a TIGTA report at tigta.gov. Speech bubble "
        "(Harry): \"IRS never calls — they mail letters.\""
    )),
    ("phone-impersonation-government", "scam-3", "sheriff-missed-jury-duty-bond", "priya", (
        "Panel 1: Priya at her office desk answers her cell phone. "
        "Speech bubble (voice): \"Deputy Williams — bench warrant for "
        "missed jury duty, deputies en route.\"\n"
        "Panel 2: The voice tells Priya to drive to the courthouse "
        "parking lot with $1,500 cash to clear the warrant. Speech "
        "bubble (voice): \"Hand the cash to a uniformed officer.\"\n"
        "Panel 3: Priya hangs up and calls her county courthouse's "
        "published number directly. Speech bubble (real court clerk): "
        "\"No warrant — courts never collect bond by phone.\"\n"
        "Panel 4: Priya reports the call to the sheriff's non-emergency "
        "line and the FTC. Speech bubble (Priya): \"Real courts use "
        "mail, not parking lots.\""
    )),
    ("phone-impersonation-government", "scam-4", "ice-cbp-deportation-threat", "marcus", (
        "Panel 1: Marcus at his apartment desk answers his cell phone; "
        "the caller-ID display reads 'ICE Field Office'. Speech bubble "
        "(voice): \"Officer Reyes — administrative deportation order for "
        "your visa.\"\n"
        "Panel 2: The voice instructs Marcus to drive to a 7-Eleven "
        "Bitcoin ATM and pay a $4,500 'compliance bond'. Speech bubble "
        "(voice): \"Stay on the line until the Bitcoin clears.\"\n"
        "Panel 3: Marcus hangs up and calls a free immigration legal-aid "
        "line (NILC) on his laptop. Speech bubble (real NILC attorney): "
        "\"ICE never calls to collect Bitcoin bonds — that's a scam.\"\n"
        "Panel 4: Marcus files an FTC report and shares the script "
        "warning with his Spanish-speaking neighbors. Speech bubble "
        "(Marcus): \"Real removal orders come on paper, not phones.\""
    )),
    ("phone-impersonation-government", "scam-5", "spoofed-local-pd-civil-fee", "priya", (
        "Panel 1: Priya at her apartment desk answers her cell phone; "
        "the caller-ID display reads her city's police-department non-"
        "emergency number. Speech bubble (voice): \"You're a witness in "
        "an active investigation — $400 civil filing fee due today.\"\n"
        "Panel 2: The voice tells Priya to pay the fee in gift cards. "
        "Speech bubble (voice): \"Apple gift cards, read me the codes.\"\n"
        "Panel 3: Priya hangs up and calls her local PD's non-emergency "
        "line directly from city-name.gov. Speech bubble (real PD "
        "dispatcher): \"We never collect fees by gift card.\"\n"
        "Panel 4: Priya reports the spoofed call to the local PD and "
        "the FTC. Speech bubble (Priya): \"Caller ID can be spoofed — "
        "the script tells you what's real.\""
    )),
    # ============================================================
    # ADVANCE-FEE LOAN & DEBT-RELIEF SCAMS (5 variants)
    # ============================================================
    ("advance-fee-loan-and-debt-relief", "scam-1", "bad-credit-guaranteed-approval-loan", "priya", (
        "Panel 1: Priya at her apartment desk answers a robocall on her "
        "phone. Speech bubble (voice): \"Pre-approved for a $5,000 loan "
        "regardless of credit — Acme Lending Group.\"\n"
        "Panel 2: A live operator demands $400 'first-month insurance' "
        "via Cash App. Speech bubble (operator): \"Send the $400 to lock "
        "in the loan.\"\n"
        "Panel 3: Priya searches the lender on her state Department of "
        "Banking website. Speech bubble (state-website): \"NOT "
        "LICENSED.\"\n"
        "Panel 4: Priya files an FTC + CFPB report and applies at her "
        "local credit union instead. Speech bubble (Priya): \"Real "
        "lenders deduct fees from disbursement.\""
    )),
    ("advance-fee-loan-and-debt-relief", "scam-2", "student-loan-forgiveness-doe-impersonation", "marcus", (
        "Panel 1: Marcus at his desk reads a Facebook ad on his laptop. "
        "Speech bubble (ad): \"Federal Loan Forgiveness Program — qualify "
        "in 5 minutes.\"\n"
        "Panel 2: A 'USA Student Debt Relief' agent demands $899 "
        "enrollment + $39/month on a phone call. Speech bubble (agent): "
        "\"We'll handle the PSLF application for you.\"\n"
        "Panel 3: Marcus opens studentaid.gov directly and finds the "
        "free PSLF application. Speech bubble (studentaid.gov): \"Apply "
        "for PSLF — Free.\"\n"
        "Panel 4: Marcus files the FREE PSLF form himself and reports "
        "the scam to the FTC. Speech bubble (Marcus): \"Real federal "
        "forgiveness costs $0 to apply for.\""
    )),
    ("advance-fee-loan-and-debt-relief", "scam-3", "credit-repair-remove-items-illegal", "priya", (
        "Panel 1: Priya at her laptop sees an Instagram ad. Speech "
        "bubble (ad): \"Boost your credit score by 120+ points in 60 "
        "days.\"\n"
        "Panel 2: A salesman demands $999 setup + $99/month over the "
        "phone. Speech bubble (salesman): \"We have insider relationships "
        "with the bureaus.\"\n"
        "Panel 3: Priya checks the federal Credit Repair Organizations "
        "Act on the FTC website. Speech bubble (FTC website): \"CROA "
        "BANS UPFRONT FEES.\"\n"
        "Panel 4: Priya disputes inaccurate items at "
        "annualcreditreport.com directly for free. Speech bubble "
        "(Priya): \"DIY credit repair is free and federally protected.\""
    )),
    ("advance-fee-loan-and-debt-relief", "scam-4", "mortgage-modification-mars-illegal", "harry", (
        "Panel 1: Harry at his kitchen table opens a 'Foreclosure "
        "Defense Group' mailer. Speech bubble (mailer): \"Save Your Home "
        "— $3,500 upfront.\"\n"
        "Panel 2: A salesman calls and demands $3,500 wire transfer plus "
        "$200/month case management. Speech bubble (salesman): \"We'll "
        "negotiate a 30% principal reduction.\"\n"
        "Panel 3: Harry checks the FTC's MARS rule on his laptop. Speech "
        "bubble (FTC website): \"MARS BANS UPFRONT FEES.\"\n"
        "Panel 4: Harry calls his loan servicer directly + a HUD-"
        "approved counselor. Speech bubble (real HUD counselor): "
        "\"Modification help is free — let's apply.\""
    )),
    ("advance-fee-loan-and-debt-relief", "scam-5", "fake-government-grant-free-money", "margie", (
        "Panel 1: Margie at her kitchen counter reads a Facebook DM "
        "from what looks like a friend. Speech bubble (DM): \"I got "
        "$25,000 from the Senior Assistance Grant — you should apply!\"\n"
        "Panel 2: A 'government agent' demands $850 'delivery fee' via "
        "Cash App over the same DM. Speech bubble (agent): \"Send the "
        "fee to release the grant.\"\n"
        "Panel 3: Margie searches grants.gov for 'Senior Assistance "
        "Grant' on her laptop. Speech bubble (grants.gov): \"NO RESULTS "
        "FOUND.\"\n"
        "Panel 4: Margie reports the impersonated friend's account and "
        "the scam to the FTC. Speech bubble (Margie): \"Real federal "
        "grants live on grants.gov — if not there, not real.\""
    )),
    # ============================================================
    # SUBSCRIPTION-TRAP & FREE-TRIAL SCAMS (5 variants)
    # ============================================================
    ("subscription-trap-and-free-trial", "scam-1", "free-trial-auto-enrollment", "priya", (
        "Panel 1: Priya at her apartment desk on her laptop, signing up "
        "for a '7-day free trial' of Speechify. Speech bubble (Priya): "
        "\"Free for a week — I'll cancel before day 7.\"\n"
        "Panel 2: Eight days later her credit-card app pings with a "
        "$229.99 charge. Speech bubble (Priya): \"Annual auto-renewal? "
        "I forgot.\"\n"
        "Panel 3: Priya cancels via Capital One Eno — locks the virtual "
        "card she used for the trial. Speech bubble (Capital One Eno "
        "app): \"VIRTUAL CARD LOCKED.\"\n"
        "Panel 4: Priya disputes the charge under FCBA + sets a calendar "
        "alert for next time. Speech bubble (Priya): \"Virtual card + "
        "calendar reminder defeats every free trial.\""
    )),
    ("subscription-trap-and-free-trial", "scam-2", "hidden-subscription-pdf-apps", "marcus", (
        "Panel 1: Marcus at his desk searches 'convert PDF online' on "
        "his laptop. Speech bubble (Marcus): \"Just need this one "
        "conversion.\"\n"
        "Panel 2: A site charges $1 for the conversion. Marcus pays. "
        "Three weeks later his card is hit with a $39.99 'premium "
        "subscription' charge. Speech bubble (card-app notification): "
        "\"$39.99 PDFPaw subscription.\"\n"
        "Panel 3: Marcus disputes the charge under FCBA + reports to "
        "the FTC. Speech bubble (FTC ReportFraud): \"REPORT FILED.\"\n"
        "Panel 4: Marcus uses LibreOffice for free PDF conversion next "
        "time. Speech bubble (Marcus): \"$1 sites are bait — the "
        "subscription is the trap.\""
    )),
    ("subscription-trap-and-free-trial", "scam-3", "bundled-checkout-prime-auto-enrollment", "harry", (
        "Panel 1: Harry at his laptop checking out on Amazon. The "
        "checkout page shows a prominent 'Continue with Prime' button "
        "and a tiny 'No, thanks' link. Speech bubble (Harry): \"Just "
        "trying to buy this one item.\"\n"
        "Panel 2: A month later Harry's card is hit with a $14.99 Prime "
        "charge he didn't intend. Speech bubble (card-app): \"AMAZON "
        "PRIME $14.99/mo.\"\n"
        "Panel 3: Harry checks the FTC's Amazon $2.5B refund-claim "
        "portal on his laptop. Speech bubble (FTC website): \"FILE "
        "CLAIM.\"\n"
        "Panel 4: Harry files the refund claim + always reads checkout "
        "boxes now. Speech bubble (Harry): \"Pre-checked boxes are "
        "subscription enrollments.\""
    )),
    ("subscription-trap-and-free-trial", "scam-4", "cancellation-labyrinth-uber-23-screens", "priya", (
        "Panel 1: Priya at her phone trying to cancel Uber One. The app "
        "shows screen 1 of a 23-screen cancellation flow. Speech bubble "
        "(app): \"Are you sure? Get 50% off!\"\n"
        "Panel 2: Priya is on screen 12, tapping through retention "
        "loops. Speech bubble (Priya): \"This is the labyrinth the FTC "
        "complaint mentioned.\"\n"
        "Panel 3: Priya gives up, sends written cancellation by certified "
        "mail + disputes the charge with her card issuer. Speech bubble "
        "(certified-mail receipt): \"DELIVERED.\"\n"
        "Panel 4: Priya's card issuer blocks Uber from billing further. "
        "Speech bubble (real card issuer): \"Merchant blocked under "
        "ROSCA.\""
    )),
    ("subscription-trap-and-free-trial", "scam-5", "weekly-billing-wellness-app-trap", "marcus", (
        "Panel 1: Marcus on his phone downloads a free 'Breeze "
        "Wellbeing' app. The first-launch screen demands $9.99/week "
        "premium. Speech bubble (app): \"$9.99/week — try premium.\"\n"
        "Panel 2: Marcus pauses and converts $9.99/week to annual on a "
        "calculator. Speech bubble (calculator): \"$519/YEAR.\"\n"
        "Panel 3: Marcus rejects the prompt and uninstalls the app. "
        "Speech bubble (Marcus): \"Weekly framing hides annual cost.\"\n"
        "Panel 4: Marcus posts a warning on r/Scams about the weekly-"
        "billing pattern. Speech bubble (r/Scams post): \"Always convert "
        "weekly to annual first.\""
    )),
    # ============================================================
    # RENTAL SCAMS (5 variants)
    # ============================================================
    ("rental-scams", "scam-1", "facebook-craigslist-fake-apartment", "priya", (
        "Panel 1: Priya at her laptop sees a Facebook Marketplace "
        "listing: '1BR Austin $1,400/mo' (market rate $2,200). Speech "
        "bubble (Priya): \"Below market — too good?\"\n"
        "Panel 2: The 'landlord' messages saying he's overseas, asks for "
        "$2,800 Zelle deposit before any tour. Speech bubble (landlord): "
        "\"Send Zelle to lock the unit today.\"\n"
        "Panel 3: Priya reverse-image-searches the listing photos. "
        "Speech bubble (Google Images): \"Same photos on Zillow — "
        "different city.\"\n"
        "Panel 4: Priya reports the listing to Facebook + finds a "
        "verified listing on Apartments.com instead. Speech bubble "
        "(Priya): \"Verified platforms only.\""
    )),
    ("rental-scams", "scam-2", "hijacked-zillow-listing", "marcus", (
        "Panel 1: Marcus at his desk reads a Facebook listing: same "
        "photos as a Zillow listing he saw earlier, but $1,000/mo "
        "cheaper. Speech bubble (Marcus): \"Same photos, different "
        "price.\"\n"
        "Panel 2: The 'agent' uses a near-lookalike email of the real "
        "Denver agency. Speech bubble (email): \"info@denver-realty.com "
        "(real: denverrealty.com).\"\n"
        "Panel 3: Marcus contacts the real agent through Zillow's "
        "verified flow. Speech bubble (real agent): \"That's a hijacked "
        "listing — actual rent is $2,950.\"\n"
        "Panel 4: Marcus reports the cloned listing to Facebook + the "
        "real agency's fraud team. Speech bubble (Marcus): \"Reverse-"
        "image-search catches every hijack.\""
    )),
    ("rental-scams", "scam-3", "vrbo-vacation-rental-fake", "harry", (
        "Panel 1: Harry at his laptop books a beach house on VRBO at "
        "$4,200/week (market rate $7,500). Speech bubble (Harry): \"Big "
        "discount for spring break.\"\n"
        "Panel 2: The host messages: 'Save 10% more if you Zelle me "
        "directly off-platform.' Speech bubble (Harry): \"That's the "
        "diagnostic.\"\n"
        "Panel 3: Harry refuses, books on Airbnb instead with credit-"
        "card payment through-platform. Speech bubble (Harry): \"Pay "
        "through-platform with credit card only.\"\n"
        "Panel 4: Harry arrives at a verified Airbnb that matches the "
        "listing. Speech bubble (Harry): \"Airbnb pays hosts after "
        "check-in — the structural protection.\""
    )),
    ("rental-scams", "scam-4", "section-8-voucher-fast-track", "margie", (
        "Panel 1: Margie at her kitchen table reads a Facebook group "
        "post: 'Section 8 fast-track placement — $750 fee.' Speech "
        "bubble (post): \"Guaranteed approval in 30 days.\"\n"
        "Panel 2: The 'specialist' demands $750 Zelle to start the "
        "process. Speech bubble (specialist): \"Send Zelle to expedite "
        "your voucher.\"\n"
        "Panel 3: Margie calls her local Public Housing Authority "
        "directly from hud.gov/phacontact. Speech bubble (real PHA "
        "rep): \"No third party can speed up Section 8 — it's free "
        "through us.\"\n"
        "Panel 4: Margie reports the scam to the FTC + helps her "
        "neighbor avoid it. Speech bubble (Margie): \"Real PHA = free. "
        "Anyone charging is a scam.\""
    )),
    ("rental-scams", "scam-5", "ai-deepfake-fabricated-listing", "priya", (
        "Panel 1: Priya at her laptop sees a Facebook listing with "
        "professional-looking photos at $1,300/mo. Reverse-image search "
        "returns no hits. Speech bubble (Priya): \"No hits — but is it "
        "real?\"\n"
        "Panel 2: Priya zooms in on the photos and notices subtle AI "
        "artifacts — repeating patterns, odd shadows. Speech bubble "
        "(Priya): \"AI-generated photos.\"\n"
        "Panel 3: Priya searches the address in the county property-"
        "records portal. Speech bubble (county website): \"Owner: not "
        "the listed landlord.\"\n"
        "Panel 4: Priya reports the listing + warns r/Scams about the "
        "AI-deepfake variant. Speech bubble (Priya): \"AI bypasses "
        "reverse-image search — property records still work.\""
    )),
    # ============================================================
    # QR CODE SCAMS (5 variants)
    # ============================================================
    ("qr-code-scams", "scam-1", "parking-meter-sticker-overlay", "priya", (
        "Panel 1: Priya at a city parking meter notices a fresh QR-code "
        "sticker on top of an etched code. Speech bubble (Priya): "
        "\"That sticker wasn't there yesterday.\"\n"
        "Panel 2: Priya peels back the sticker and sees the real "
        "etched QR underneath. Speech bubble (Priya): \"Sticker overlay "
        "= scam.\"\n"
        "Panel 3: Priya opens the official ParkNYC app on her phone "
        "directly. Speech bubble (ParkNYC app): \"PAYMENT SUCCESS.\"\n"
        "Panel 4: Priya reports the tampered meter to NYC DOT. Speech "
        "bubble (Priya): \"Type the URL or use the official app — never "
        "scan a sticker QR.\""
    )),
    ("qr-code-scams", "scam-2", "restaurant-menu-qr-sticker", "marcus", (
        "Panel 1: Marcus at a restaurant table sees a QR code on a "
        "fresh paper sticker on the laminated menu. Speech bubble "
        "(Marcus): \"Sticker on top of the printed menu — suspicious.\"\n"
        "Panel 2: Marcus asks the server to confirm the URL. Speech "
        "bubble (server): \"That's not our URL — someone tampered.\"\n"
        "Panel 3: The server peels off the fake sticker and gives "
        "Marcus the printed bill instead. Speech bubble (server): "
        "\"Pay at the counter — we'll alert management.\"\n"
        "Panel 4: Marcus pays with a card-tap at the counter. Speech "
        "bubble (Marcus): \"Server-mediated payment beats QR every "
        "time.\""
    )),
    ("qr-code-scams", "scam-3", "unsolicited-package-qr-code", "harry", (
        "Panel 1: Harry finds an unsolicited package on his doorstep "
        "with a QR code labeled 'Scan to identify sender.' Speech "
        "bubble (Harry): \"I didn't order this.\"\n"
        "Panel 2: Harry checks the FBI's 2025 alert page on his laptop. "
        "Speech bubble (FBI alert): \"DO NOT SCAN — Unsolicited-package "
        "QR-code fraud.\"\n"
        "Panel 3: Harry calls the carrier directly through the number "
        "on USPS.com to verify the package. Speech bubble (real USPS "
        "rep): \"No record of this delivery — discard.\"\n"
        "Panel 4: Harry disposes of the package without scanning. "
        "Speech bubble (Harry): \"Unexpected package + QR code = FBI-"
        "documented scam.\""
    )),
    ("qr-code-scams", "scam-4", "toll-text-qr-scam", "priya", (
        "Panel 1: Priya gets a text on her phone: 'E-ZPass: $12.75 "
        "outstanding toll — scan QR to pay.' Speech bubble (text): "
        "\"Avoid $50 late fee.\"\n"
        "Panel 2: Priya pauses — real E-ZPass mails notices, never "
        "texts. Speech bubble (Priya): \"Toll authority never texts.\"\n"
        "Panel 3: Priya types e-zpassny.com directly into her browser "
        "and logs in. Speech bubble (real E-ZPass): \"NO OUTSTANDING "
        "BALANCE.\"\n"
        "Panel 4: Priya forwards the scam text to 7726 and her state "
        "DOT. Speech bubble (Priya): \"Type the URL — toll texts are "
        "always fake.\""
    )),
    ("qr-code-scams", "scam-5", "corporate-quishing-email-qr", "marcus", (
        "Panel 1: Marcus at his office desk sees an email from 'IT' "
        "with a QR code: 'Password expires in 24 hours — scan to "
        "reset.' Speech bubble (Marcus): \"QR code in an email?\"\n"
        "Panel 2: Marcus opens his company's IT-helpdesk Slack channel "
        "to verify. Speech bubble (real IT-security): \"That's a "
        "phishing email — we never send QR codes.\"\n"
        "Panel 3: Marcus reports the email to IT-security via Slack. "
        "Speech bubble (real IT rep): \"Forwarded to email-security — "
        "thanks for not scanning.\"\n"
        "Panel 4: Marcus changes his password through the SSO portal "
        "directly (typed URL). Speech bubble (Marcus): \"IT-helpdesk "
        "verification beats every email QR.\""
    )),
    # ============================================================
    # SOCIAL MEDIA ACCOUNT TAKEOVER (5 variants)
    # ============================================================
    ("social-media-account-takeover", "scam-1", "phishing-link-instagram-login", "priya", (
        "Panel 1: Priya at her laptop reads an email from "
        "'notification-instagram.com': 'Account violates community "
        "guidelines — verify identity in 24h.' Speech bubble (Priya): "
        "\"Domain isn't instagram.com.\"\n"
        "Panel 2: Priya opens the official Instagram app instead of "
        "clicking the link. Speech bubble (Instagram app): \"NO "
        "VIOLATIONS — ACCOUNT ACTIVE.\"\n"
        "Panel 3: Priya enables authenticator-app 2FA in Settings → "
        "Security. Speech bubble (Authy app): \"2FA ACTIVATED.\"\n"
        "Panel 4: Priya reports the phishing email to Meta. Speech "
        "bubble (Priya): \"Type the URL or use the official app — never "
        "click email login links.\""
    )),
    ("social-media-account-takeover", "scam-2", "friend-recovery-code-hijack", "margie", (
        "Panel 1: Margie at her kitchen counter gets a Messenger DM "
        "from her best friend: 'I'm locked out — Facebook is sending a "
        "code to your phone, can you forward it?' Speech bubble (DM): "
        "\"Just screenshot it.\"\n"
        "Panel 2: Margie's phone receives an SMS: 'Your Facebook code "
        "is 837492.' Margie pauses. Speech bubble (Margie): \"Why am I "
        "getting a code?\"\n"
        "Panel 3: Margie calls her friend on her real phone number "
        "instead. Speech bubble (real friend): \"I never sent that DM — "
        "my account is hacked.\"\n"
        "Panel 4: Margie changes her password + enables 2FA. Speech "
        "bubble (Margie): \"Never forward verification codes — even to "
        "friends.\""
    )),
    ("social-media-account-takeover", "scam-3", "blue-check-verification-phishing", "marcus", (
        "Panel 1: Marcus at his desk sees an email: 'Meta Verified "
        "Support — verification expires in 48h, submit ID + selfie.' "
        "Speech bubble (Marcus): \"Meta never asks for ID by email.\"\n"
        "Panel 2: Marcus opens the official Instagram app, navigates "
        "to Settings → Account → Meta Verified. Speech bubble "
        "(Instagram app): \"VERIFIED STATUS: ACTIVE.\"\n"
        "Panel 3: Marcus reports the phishing email to Meta + the FTC. "
        "Speech bubble (Marcus): \"Verification is managed in-app, "
        "never via email.\"\n"
        "Panel 4: Marcus updates his password manager + reviews active "
        "sessions. Speech bubble (Marcus): \"Strong password + auth-app "
        "2FA + never share ID.\""
    )),
    ("social-media-account-takeover", "scam-4", "hijacked-friend-crypto-pitch", "harry", (
        "Panel 1: Harry on his laptop sees a Facebook post from his "
        "cousin: 'Made $8K in two weeks on this trading platform — DM "
        "for the link.' Speech bubble (Harry): \"Cousin doesn't talk "
        "about crypto.\"\n"
        "Panel 2: Harry calls his cousin on her real phone number to "
        "verify. Speech bubble (real cousin): \"I never posted that — "
        "my account is hacked.\"\n"
        "Panel 3: Harry reports the post to Facebook + warns the "
        "cousin's followers via group text. Speech bubble (Harry): "
        "\"Real friends don't pitch trading platforms.\"\n"
        "Panel 4: Cousin recovers her account through facebook.com/"
        "hacked. Speech bubble (Harry): \"Cross-channel verification "
        "defeats hijacked-account crypto pitches.\""
    )),
    ("social-media-account-takeover", "scam-5", "account-recovery-scam-followon", "priya", (
        "Panel 1: Priya posts on r/Scams: 'My Instagram got hacked, "
        "Meta recovery is taking days.' Speech bubble (Priya): "
        "\"Anyone have advice?\"\n"
        "Panel 2: Within hours, multiple DMs offer 'account recovery "
        "specialist' services for $500-$2,000 upfront. Speech bubble "
        "(DM): \"I can recover your account in 24h.\"\n"
        "Panel 3: Priya checks Meta's official path at instagram.com/"
        "hacked — the only legitimate route. Speech bubble (Meta site): "
        "\"FREE OFFICIAL RECOVERY.\"\n"
        "Panel 4: Priya blocks all recovery DMs + waits for Meta's "
        "verification. Speech bubble (Priya): \"100% of third-party "
        "recovery services are scams.\""
    )),
    # ============================================================
    # AMAZON & REFUND SCAMS (5 variants)
    # ============================================================
    ("amazon-and-refund-scams", "scam-1", "fake-refund-text", "margie", (
        "Panel 1: Margie at her kitchen counter gets a text on her "
        "phone: 'AMAZON: Routine quality inspection — full refund "
        "available, click to claim.' Speech bubble (text): \"$47.99 "
        "REFUND PENDING.\"\n"
        "Panel 2: Margie pauses and opens the official Amazon app "
        "instead of clicking the link. Speech bubble (Amazon app): "
        "\"NO PENDING REFUNDS.\"\n"
        "Panel 3: Margie forwards the scam text to 7726 + reports to "
        "stop-spoofing@amazon.com. Speech bubble (Margie): \"Real "
        "refunds appear in the app.\"\n"
        "Panel 4: Margie deletes the text + warns her neighbor about "
        "the scam pattern. Speech bubble (Margie): \"Click the app, "
        "never the text link.\""
    )),
    ("amazon-and-refund-scams", "scam-2", "prime-auto-renewal-phishing", "harry", (
        "Panel 1: Harry at his desk reads an email: 'Your Prime "
        "auto-renews tomorrow at $249.99 — click to cancel.' Speech "
        "bubble (Harry): \"Prime is $139, not $249.\"\n"
        "Panel 2: Harry opens amazon.com directly and checks Manage "
        "Prime Membership. Speech bubble (Amazon page): \"NEXT RENEWAL: "
        "$139.00.\"\n"
        "Panel 3: Harry forwards the phishing email to stop-spoofing@"
        "amazon.com + enables auth-app 2FA. Speech bubble (Authy): "
        "\"AMAZON 2FA ACTIVATED.\"\n"
        "Panel 4: Harry warns his Prime-using friends about the $249 "
        "tell. Speech bubble (Harry): \"Wrong renewal price = "
        "diagnostic for fraud.\""
    )),
    ("amazon-and-refund-scams", "scam-3", "amazon-account-takeover-call", "margie", (
        "Panel 1: Margie at her kitchen counter answers her phone — "
        "caller-ID reads 'Amazon Customer Service.' Speech bubble "
        "(voice): \"Your account has 5 unauthorized purchases — "
        "verify the 2FA code we just sent.\"\n"
        "Panel 2: Margie's phone shows a 6-digit Amazon 2FA code SMS. "
        "She pauses. Speech bubble (Margie): \"Amazon never asks for "
        "the code.\"\n"
        "Panel 3: Margie hangs up and logs into amazon.com directly to "
        "check for any actual issue. Speech bubble (Amazon page): \"NO "
        "ISSUES — ACCOUNT ACTIVE.\"\n"
        "Panel 4: Margie reports the call to stop-spoofing@amazon.com "
        "+ FTC. Speech bubble (Margie): \"Amazon CS never asks for "
        "codes — that's the scam.\""
    )),
    ("amazon-and-refund-scams", "scam-4", "product-recall-scam", "marcus", (
        "Panel 1: Marcus on his phone gets a text: 'AMAZON RECALL: "
        "Your recent purchase of [item] has been recalled — click for "
        "refund.' Speech bubble (Marcus): \"Real recalls live on "
        "cpsc.gov.\"\n"
        "Panel 2: Marcus opens cpsc.gov/recalls on his laptop and "
        "searches the product. Speech bubble (CPSC website): \"NO "
        "RECALLS FOUND.\"\n"
        "Panel 3: Marcus also checks his Amazon account → Recall "
        "Notifications. Speech bubble (Amazon page): \"NO RECALL "
        "NOTIFICATIONS.\"\n"
        "Panel 4: Marcus forwards the text to 7726 + reports to "
        "stop-spoofing@amazon.com. Speech bubble (Marcus): \"Cross-"
        "check at cpsc.gov + Amazon account directly.\""
    )),
    ("amazon-and-refund-scams", "scam-5", "refund-overpayment-remote-access", "harry", (
        "Panel 1: Harry at his laptop on a phone call with an 'Amazon "
        "refund agent.' The agent has him install AnyDesk to 'process "
        "the refund.' Speech bubble (voice): \"Install AnyDesk to "
        "verify your refund.\"\n"
        "Panel 2: The agent fakes a $5,000 overpayment on Harry's bank "
        "screen via remote control. Speech bubble (voice): \"You got "
        "$5,000 instead of $50 — wire $4,950 back!\"\n"
        "Panel 3: Harry recognizes the script — Amazon never uses "
        "remote-access tools. He unplugs the laptop ethernet + powers "
        "it off. Speech bubble (Harry): \"Amazon never installs "
        "AnyDesk.\"\n"
        "Panel 4: Harry calls his real bank from a different device to "
        "lock his accounts. Speech bubble (real bank rep): \"Your "
        "accounts are secured.\""
    )),
    # ============================================================
    # CHECK FRAUD & OVERPAYMENT (5 variants)
    # ============================================================
    ("check-fraud-and-overpayment", "scam-1", "mail-theft-check-washing", "harry", (
        "Panel 1: Harry drops a $1,800 mortgage check into his "
        "residential mailbox + raises the flag. Speech bubble (Harry): "
        "\"Bills mailed.\"\n"
        "Panel 2: A thief in a car at night reaches into Harry's mailbox "
        "and grabs the envelope. Speech bubble (thief): \"Flag's up — "
        "perfect.\"\n"
        "Panel 3: Two weeks later Harry's bank statement shows a "
        "$9,800 debit instead of $1,800. Speech bubble (Harry): \"Check "
        "got washed.\"\n"
        "Panel 4: Harry switches to ACH bill-pay + reports to USPIS at "
        "uspis.gov/report. Speech bubble (Harry): \"Mail at the post "
        "office, never the box.\""
    )),
    ("check-fraud-and-overpayment", "scam-2", "marketplace-overpayment", "priya", (
        "Panel 1: Priya at her laptop reads a Facebook Marketplace "
        "buyer's offer. Speech bubble (buyer): \"Cashier check for "
        "$2,800 — please Zelle me back the $2,000 difference.\"\n"
        "Panel 2: The check arrives — looks legitimate. Priya pauses. "
        "Speech bubble (Priya): \"Real buyers don't accidentally "
        "overpay.\"\n"
        "Panel 3: Priya calls her bank: 'Has this cleared, or is it "
        "provisional?' Speech bubble (real bank rep): \"PROVISIONAL — "
        "could take 2-4 weeks.\"\n"
        "Panel 4: Priya returns the check uncashed + asks for Zelle "
        "G&S for the actual price. Speech bubble (Priya): \"Wait for "
        "full clearance — never wire 'overpayment' back.\""
    )),
    ("check-fraud-and-overpayment", "scam-3", "secret-shopper-fake-check", "marcus", (
        "Panel 1: Marcus on his phone reads a DM: 'Mystery Shopper "
        "Position — $500/assignment.' Speech bubble (DM): \"Free "
        "training, work from home.\"\n"
        "Panel 2: A $4,000 check arrives FedEx with instructions to buy "
        "$3,500 in MoneyGram money orders as the 'evaluation.' Speech "
        "bubble (instructions): \"Photograph + send codes back.\"\n"
        "Panel 3: Marcus checks the MSPA-NA directory for the firm — "
        "no match. Speech bubble (Marcus): \"Real firms pay AFTER "
        "work, via direct deposit.\"\n"
        "Panel 4: Marcus reports the scam at FTC + tears up the check. "
        "Speech bubble (Marcus): \"Pre-work checks = fraud.\""
    )),
    ("check-fraud-and-overpayment", "scam-4", "job-offer-first-paycheck", "priya", (
        "Panel 1: Priya at her desk gets a FedEx envelope from a new "
        "'employer' with a $3,500 cashier's check. Speech bubble "
        "(letter): \"Equipment funds — Zelle $2,800 to our preferred "
        "vendor.\"\n"
        "Panel 2: Priya pauses. Real employers ship equipment via IT, "
        "not via employee-purchased equipment. Speech bubble (Priya): "
        "\"Real employers ship gear directly.\"\n"
        "Panel 3: Priya searches the company on LinkedIn — no real "
        "employees match the recruiter. Speech bubble (Priya): \"Fake "
        "employer.\"\n"
        "Panel 4: Priya reports to FTC + the impersonated company's "
        "security team. Speech bubble (Priya): \"Pre-employment checks "
        "are always fraud.\""
    )),
    ("check-fraud-and-overpayment", "scam-5", "lottery-advance-fee-check", "margie", (
        "Panel 1: Margie at her kitchen counter opens a mailed letter: "
        "'You won $250,000! $5,000 advance check enclosed for taxes.' "
        "Speech bubble (letter): \"Wire $4,200 to release prize.\"\n"
        "Panel 2: Margie pauses — she never entered any sweepstakes. "
        "Speech bubble (Margie): \"Real lotteries deduct taxes from the "
        "prize, not in advance.\"\n"
        "Panel 3: Margie calls her son for verification. Speech bubble "
        "(real son): \"Mom — that's a sweepstakes scam. Tear it up.\"\n"
        "Panel 4: Margie shreds the letter + reports to USPIS + FTC. "
        "Speech bubble (Margie): \"If I didn't enter, I didn't win.\""
    )),
    # ============================================================
    # CAR-BUYING SCAMS (5 variants)
    # ============================================================
    ("car-buying-scams", "scam-1", "fake-escrow-scam", "harry", (
        "Panel 1: Harry at his laptop reads a buyer's message: 'Use "
        "ShieldEscrowServices.com — I'm relocating from Ohio.' Speech "
        "bubble (Harry): \"Never heard of that escrow service.\"\n"
        "Panel 2: A 'funds held' screenshot arrives via email — looks "
        "convincing. Speech bubble (Harry): \"But it's just a "
        "screenshot, not a verified bank transfer.\"\n"
        "Panel 3: Harry refuses + counter-proposes Escrow.com or "
        "in-person bank closing. Speech bubble (Harry): \"Real escrow "
        "via Escrow.com or in-person at my bank only.\"\n"
        "Panel 4: Harry sells the car to a verified local buyer at his "
        "bank. Speech bubble (real bank teller): \"CASHIER'S CHECK "
        "VERIFIED.\""
    )),
    ("car-buying-scams", "scam-2", "vin-cloning", "marcus", (
        "Panel 1: Marcus at his laptop sees a 2020 4Runner on "
        "Craigslist for $32,000 (market $36,000). Speech bubble "
        "(Marcus): \"Slightly below market — needs a careful check.\"\n"
        "Panel 2: Marcus brings the 4Runner to his mechanic for a "
        "pre-purchase inspection. The mechanic checks VINs at engine, "
        "dash, doors. Speech bubble (mechanic): \"Engine VIN doesn't "
        "match dashboard.\"\n"
        "Panel 3: Marcus runs the VIN through NMVTIS at "
        "vehiclehistory.gov. Speech bubble (NMVTIS): \"VIN registered "
        "to different vehicle in Texas.\"\n"
        "Panel 4: Marcus walks away + reports to local police. Speech "
        "bubble (Marcus): \"Cloned VIN — three-source check caught "
        "it.\""
    )),
    ("car-buying-scams", "scam-3", "curbstoning", "priya", (
        "Panel 1: Priya at a Walmart parking lot meets seller 'John' "
        "selling a 2017 Explorer at $12,500. Speech bubble (John): "
        "\"Cash only, no paperwork until after the sale.\"\n"
        "Panel 2: Priya searches John's phone number on Facebook "
        "Marketplace — 12 other vehicle listings under the same number. "
        "Speech bubble (Priya): \"Curbstoner — 12 listings under one "
        "number.\"\n"
        "Panel 3: Priya walks away + reports John to her state DMV. "
        "Speech bubble (state DMV portal): \"REPORT FILED.\"\n"
        "Panel 4: Priya finds a different car from a verified private "
        "seller at their home address. Speech bubble (Priya): "
        "\"Residence + same-number search caught the curbstoner.\""
    )),
    ("car-buying-scams", "scam-4", "vehicle-history-report-harvest", "marcus", (
        "Panel 1: Marcus selling his Honda Accord on Craigslist gets a "
        "buyer message: 'Need a report from VinHistoryCheck.com first.' "
        "Speech bubble (buyer): \"Pay $34.99 + send me the report.\"\n"
        "Panel 2: Marcus pauses — real Carfax/AutoCheck reports are paid "
        "by the buyer, not the seller. Speech bubble (Marcus): \"Buyer "
        "pays for due diligence.\"\n"
        "Panel 3: Marcus refuses + offers Carfax instead. Speech bubble "
        "(Marcus): \"Carfax or AutoCheck — your cost, not mine.\"\n"
        "Panel 4: Buyer disappears. Marcus reports to FTC + Craigslist. "
        "Speech bubble (Marcus): \"Niche history-report sites are "
        "credit-card harvest scams.\""
    )),
    ("car-buying-scams", "scam-5", "overseas-buyer-wire-fraud", "harry", (
        "Panel 1: Harry selling a Civic gets a message: 'I'm Navy, "
        "deployed overseas — full asking + $700 shipping.' Speech "
        "bubble (buyer): \"Pay you via cashier's check for $14K total.\"\n"
        "Panel 2: A $14,000 cashier's check arrives — buyer asks Harry "
        "to wire $3,500 to 'shipping company' from the funds. Speech "
        "bubble (Harry): \"Real military buyers don't buy sight-"
        "unseen.\"\n"
        "Panel 3: Harry calls his bank: 'Has this cleared?' Speech "
        "bubble (real bank rep): \"PROVISIONAL — 2-4 weeks for "
        "clearance.\"\n"
        "Panel 4: Harry returns the check + reports to FTC + IC3. "
        "Speech bubble (Harry): \"Overseas-buyer wire fraud = check-"
        "fraud guide variant 5.\""
    )),
    # ============================================================
    # CHARITY & DISASTER SCAMS (5 variants)
    # ============================================================
    ("charity-and-disaster-scams", "scam-1", "fake-gofundme-fabricated-victims", "priya", (
        "Panel 1: Priya at her laptop sees a Facebook share for a "
        "GoFundMe page: 'Help the Johnson family — lost everything in "
        "Hurricane Helene.' Speech bubble (Priya): \"Wait, that photo's "
        "from CNN's coverage.\"\n"
        "Panel 2: Priya reverse-image-searches the photo on her browser. "
        "Speech bubble (Google Images): \"News-outlet stock photo — "
        "stolen.\"\n"
        "Panel 3: Priya donates to World Central Kitchen instead via "
        "wck.org typed directly. Speech bubble (WCK site): \"VERIFIED "
        "501(c)(3) — DONATION RECEIVED.\"\n"
        "Panel 4: Priya reports the fake GoFundMe to the platform's "
        "trust-and-safety team. Speech bubble (Priya): \"Donate to "
        "established orgs, not to strangers' pages.\""
    )),
    ("charity-and-disaster-scams", "scam-2", "sound-alike-charity-organization", "marcus", (
        "Panel 1: Marcus at his laptop reads an email: 'Hurricane "
        "Helene Survivors Fund — donate now.' Speech bubble (Marcus): "
        "\"Never heard of this organization.\"\n"
        "Panel 2: Marcus searches the org name on Charity Navigator. "
        "Speech bubble (Charity Navigator): \"NO RESULTS — NOT A "
        "REGISTERED 501(c)(3).\"\n"
        "Panel 3: Marcus also checks the IRS Tax Exempt search at "
        "irs.gov. Speech bubble (IRS site): \"NO RECORD — NOT VERIFIED "
        "CHARITY.\"\n"
        "Panel 4: Marcus donates to the actual American Red Cross via "
        "redcross.org typed directly. Speech bubble (Marcus): \"Three-"
        "source verification before any donation.\""
    )),
    ("charity-and-disaster-scams", "scam-3", "fema-impersonation", "harry", (
        "Panel 1: Harry at his front door speaks to a man in a polo "
        "shirt with a 'FEMA Disaster Inspector' patch. Speech bubble "
        "(man): \"Need your SSN + bank info + $300 expedite fee for "
        "your grant.\"\n"
        "Panel 2: Harry pauses — FEMA never charges for assistance. "
        "Speech bubble (Harry): \"Real FEMA never asks for fees.\"\n"
        "Panel 3: Harry closes the door + logs into disasterassistance."
        "gov directly. Speech bubble (DisasterAssistance.gov): \"NO "
        "PENDING INSPECTION — VERIFIED.\"\n"
        "Panel 4: Harry calls the National Center for Disaster Fraud at "
        "1-866-720-5721. Speech bubble (real NCDF rep): \"Report filed "
        "— investigating impersonation.\""
    )),
    ("charity-and-disaster-scams", "scam-4", "post-disaster-contractor", "margie", (
        "Panel 1: Margie at her front door after a hurricane meets a "
        "contractor with out-of-state plates demanding $4,000 cash for "
        "roof repair. Speech bubble (contractor): \"State inspector will "
        "fine you in 72 hours — must start today.\"\n"
        "Panel 2: Margie pauses — her insurance carrier has preferred "
        "vendors. Speech bubble (Margie): \"Let me call my carrier "
        "first.\"\n"
        "Panel 3: Margie calls her insurance carrier directly. Speech "
        "bubble (real carrier): \"We'll dispatch our vetted preferred "
        "vendor at no cost.\"\n"
        "Panel 4: Margie's carrier-vetted contractor arrives + files "
        "the claim properly. Speech bubble (Margie): \"Insurance carrier "
        "first — door-to-door storm chasers second.\""
    )),
    ("charity-and-disaster-scams", "scam-5", "donation-phishing-email", "priya", (
        "Panel 1: Priya at her laptop reads an email: 'American Red "
        "Cross Emergency Appeal — donate now.' Speech bubble (Priya): "
        "\"Sender domain is 'redcross-disaster-appeal.org' — that's a "
        "lookalike.\"\n"
        "Panel 2: Priya types redcross.org directly into her browser "
        "instead. Speech bubble (Priya): \"Type the URL, not the email "
        "link.\"\n"
        "Panel 3: Priya donates through the real Red Cross site by "
        "credit card. Speech bubble (real Red Cross): \"$50 received — "
        "thank you.\"\n"
        "Panel 4: Priya reports the phishing email to FTC + Red Cross "
        "abuse address. Speech bubble (Priya): \"Type the .org URL — "
        "never click email donation links.\""
    )),
    # ============================================================
    # TELEGRAM CRYPTO PUMP & WALLET-DRAINER (5 variants)
    # ============================================================
    ("telegram-crypto-pump-and-drainer", "scam-1", "telegram-pump-and-dump", "marcus", (
        "Panel 1: Marcus at his laptop in a Telegram VIP channel sees "
        "an alert: 'PUMP ANNOUNCED — buy XYZ Token at 3:00 PM UTC.' "
        "Speech bubble (channel): \"Synchronized buy in 5 minutes!\"\n"
        "Panel 2: Marcus pauses + remembers SEC pump-and-dump "
        "enforcement actions. Speech bubble (Marcus): \"Insiders are "
        "the ones who exit at peak.\"\n"
        "Panel 3: Marcus refuses + cancels the VIP subscription. The "
        "token spikes then crashes 90%. Speech bubble (price chart): "
        "\"PEAK → DUMP\"\n"
        "Panel 4: Marcus reports the channel to SEC TCR. Speech bubble "
        "(Marcus): \"Real legitimate trading doesn't work via "
        "synchronized buys.\""
    )),
    ("telegram-crypto-pump-and-drainer", "scam-2", "wallet-drainer-inferno", "priya", (
        "Panel 1: Priya at her laptop sees an X / Twitter ad: 'Uniswap "
        "V4 early-access airdrop — claim 5,000 UNI tokens.' Speech "
        "bubble (Priya): \"That URL is uniswap-airdrop.com, not "
        "uniswap.org.\"\n"
        "Panel 2: Priya checks the announcement on Uniswap's official "
        "Twitter — no such airdrop. Speech bubble (Uniswap official): "
        "\"NO V4 AIRDROP ANNOUNCED.\"\n"
        "Panel 3: Priya runs Revoke.cash to audit existing approvals + "
        "revokes anything unused. Speech bubble (Revoke.cash): \"3 "
        "STALE APPROVALS REVOKED.\"\n"
        "Panel 4: Priya buys a hardware wallet for non-trivial holdings. "
        "Speech bubble (Priya): \"Hardware wallet + Revoke.cash audit "
        "+ no unsolicited connect.\""
    )),
    ("telegram-crypto-pump-and-drainer", "scam-3", "fake-telegram-support", "harry", (
        "Panel 1: Harry at his laptop posts in MetaMask Discord asking "
        "about a failed transaction. A DM arrives from 'MetaMask Help "
        "Desk' offering private support. Speech bubble (DM): \"Join "
        "this private support channel.\"\n"
        "Panel 2: Harry checks the channel name — 'MetaMask Help Desk' "
        "vs 'MetaMask Official' — clear lookalike. Speech bubble "
        "(Harry): \"Lookalike channel.\"\n"
        "Panel 3: The fake support agent asks for Harry's 12-word seed "
        "phrase to 'verify recovery.' Speech bubble (Harry): \"Real "
        "MetaMask never asks for the seed phrase.\"\n"
        "Panel 4: Harry blocks the DM + reports the fake channel to "
        "Discord. Speech bubble (Harry): \"Seed-phrase request = always "
        "scam.\""
    )),
    ("telegram-crypto-pump-and-drainer", "scam-4", "fake-airdrop-wallet-connect", "marcus", (
        "Panel 1: Marcus on his phone sees a viral X post: 'OpenSea "
        "Genesis Airdrop — $50,000 in free tokens.' Speech bubble "
        "(post): \"Connect wallet to claim.\"\n"
        "Panel 2: Marcus types opensea.io directly in his browser to "
        "verify. Speech bubble (real OpenSea): \"NO AIRDROP "
        "ANNOUNCED.\"\n"
        "Panel 3: Marcus closes the X post + audits his approvals via "
        "Revoke.cash. Speech bubble (Marcus): \"Free is not free if it "
        "requires a signature.\"\n"
        "Panel 4: Marcus reports the X post + the airdrop URL to "
        "Chainabuse. Speech bubble (Marcus): \"Real airdrops push "
        "automatically; claim-pages are drainers.\""
    )),
    ("telegram-crypto-pump-and-drainer", "scam-5", "fake-trading-bot-subscription", "priya", (
        "Panel 1: Priya at her laptop sees a Telegram channel "
        "advertising 'AlphaSignal Pro — $200/month for 3-5x monthly "
        "returns.' Speech bubble (ad): \"Verified members report "
        "consistent profits!\"\n"
        "Panel 2: Priya pauses — real consistent-return strategies "
        "don't sell on Telegram. Speech bubble (Priya): \"If it "
        "actually worked, why sell access?\"\n"
        "Panel 3: Priya skips the subscription + holds spot crypto in "
        "a hardware wallet instead. Speech bubble (Ledger wallet): "
        "\"PORTFOLIO SECURE.\"\n"
        "Panel 4: Priya reports the channel to FTC + SEC TCR. Speech "
        "bubble (Priya): \"No paid Telegram signal group is "
        "legitimate.\""
    )),
]

assert len(MANIFEST) == 111, f"Expected 111 entries, got {len(MANIFEST)}"
