#!/usr/bin/env python3
"""
Build emergency numbers database for all countries.
Sources: Wikipedia, RestCountries, manual curation.
Output: tabiji/app/data/emergency-numbers.json
"""

import json
import os

# Comprehensive emergency numbers database
# Sources: Wikipedia "List of emergency telephone numbers", ITU, verified against gov sources
EMERGENCY_NUMBERS = {
    "AD": {"police": "110", "ambulance": "118", "fire": "118", "universal": "112", "country": "Andorra"},
    "AE": {"police": "999", "ambulance": "998", "fire": "997", "universal": None, "country": "United Arab Emirates"},
    "AF": {"police": "119", "ambulance": "112", "fire": "119", "universal": None, "country": "Afghanistan"},
    "AG": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Antigua and Barbuda"},
    "AL": {"police": "129", "ambulance": "127", "fire": "128", "universal": "112", "country": "Albania"},
    "AM": {"police": "102", "ambulance": "103", "fire": "101", "universal": None, "country": "Armenia"},
    "AO": {"police": "113", "ambulance": "112", "fire": "115", "universal": None, "country": "Angola"},
    "AR": {"police": "101", "ambulance": "107", "fire": "100", "universal": "911", "country": "Argentina"},
    "AT": {"police": "133", "ambulance": "144", "fire": "122", "universal": "112", "country": "Austria"},
    "AU": {"police": "000", "ambulance": "000", "fire": "000", "universal": "000", "country": "Australia"},
    "AZ": {"police": "102", "ambulance": "103", "fire": "101", "universal": None, "country": "Azerbaijan"},
    "BA": {"police": "122", "ambulance": "124", "fire": "123", "universal": "112", "country": "Bosnia and Herzegovina"},
    "BB": {"police": "211", "ambulance": "511", "fire": "311", "universal": None, "country": "Barbados"},
    "BD": {"police": "999", "ambulance": "999", "fire": "999", "universal": "999", "country": "Bangladesh"},
    "BE": {"police": "101", "ambulance": "112", "fire": "112", "universal": "112", "country": "Belgium"},
    "BF": {"police": "17", "ambulance": "18", "fire": "18", "universal": None, "country": "Burkina Faso"},
    "BG": {"police": "166", "ambulance": "150", "fire": "160", "universal": "112", "country": "Bulgaria"},
    "BH": {"police": "999", "ambulance": "999", "fire": "999", "universal": "999", "country": "Bahrain"},
    "BI": {"police": "117", "ambulance": "118", "fire": "118", "universal": None, "country": "Burundi"},
    "BJ": {"police": "117", "ambulance": "118", "fire": "118", "universal": None, "country": "Benin"},
    "BN": {"police": "993", "ambulance": "991", "fire": "995", "universal": None, "country": "Brunei"},
    "BO": {"police": "110", "ambulance": "118", "fire": "119", "universal": None, "country": "Bolivia"},
    "BR": {"police": "190", "ambulance": "192", "fire": "193", "universal": None, "country": "Brazil"},
    "BS": {"police": "919", "ambulance": "919", "fire": "919", "universal": "919", "country": "Bahamas"},
    "BT": {"police": "113", "ambulance": "112", "fire": "110", "universal": None, "country": "Bhutan"},
    "BW": {"police": "999", "ambulance": "997", "fire": "998", "universal": None, "country": "Botswana"},
    "BY": {"police": "102", "ambulance": "103", "fire": "101", "universal": "112", "country": "Belarus"},
    "BZ": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Belize"},
    "CA": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Canada"},
    "CD": {"police": "112", "ambulance": "112", "fire": "118", "universal": None, "country": "DR Congo"},
    "CF": {"police": "117", "ambulance": "118", "fire": "118", "universal": None, "country": "Central African Republic"},
    "CG": {"police": "117", "ambulance": "118", "fire": "118", "universal": None, "country": "Republic of the Congo"},
    "CH": {"police": "117", "ambulance": "144", "fire": "118", "universal": "112", "country": "Switzerland"},
    "CI": {"police": "111", "ambulance": "185", "fire": "180", "universal": None, "country": "Côte d'Ivoire"},
    "CL": {"police": "133", "ambulance": "131", "fire": "132", "universal": None, "country": "Chile"},
    "CM": {"police": "117", "ambulance": "119", "fire": "118", "universal": None, "country": "Cameroon"},
    "CN": {"police": "110", "ambulance": "120", "fire": "119", "universal": None, "country": "China"},
    "CO": {"police": "112", "ambulance": "125", "fire": "119", "universal": "123", "country": "Colombia"},
    "CR": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Costa Rica"},
    "CU": {"police": "106", "ambulance": "104", "fire": "105", "universal": None, "country": "Cuba"},
    "CV": {"police": "132", "ambulance": "130", "fire": "131", "universal": None, "country": "Cape Verde"},
    "CY": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Cyprus"},
    "CZ": {"police": "158", "ambulance": "155", "fire": "150", "universal": "112", "country": "Czech Republic"},
    "DE": {"police": "110", "ambulance": "112", "fire": "112", "universal": "112", "country": "Germany"},
    "DJ": {"police": "17", "ambulance": "18", "fire": "18", "universal": None, "country": "Djibouti"},
    "DK": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Denmark"},
    "DM": {"police": "999", "ambulance": "999", "fire": "999", "universal": "999", "country": "Dominica"},
    "DO": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Dominican Republic"},
    "DZ": {"police": "17", "ambulance": "14", "fire": "14", "universal": None, "country": "Algeria"},
    "EC": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Ecuador"},
    "EE": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Estonia"},
    "EG": {"police": "122", "ambulance": "123", "fire": "180", "universal": None, "country": "Egypt"},
    "ER": {"police": "127", "ambulance": "124", "fire": "128", "universal": None, "country": "Eritrea"},
    "ES": {"police": "091", "ambulance": "112", "fire": "112", "universal": "112", "country": "Spain"},
    "ET": {"police": "991", "ambulance": "907", "fire": "939", "universal": None, "country": "Ethiopia"},
    "FI": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Finland"},
    "FJ": {"police": "917", "ambulance": "911", "fire": "910", "universal": None, "country": "Fiji"},
    "FR": {"police": "17", "ambulance": "15", "fire": "18", "universal": "112", "country": "France"},
    "GA": {"police": "1730", "ambulance": "1300", "fire": "18", "universal": None, "country": "Gabon"},
    "GB": {"police": "999", "ambulance": "999", "fire": "999", "universal": "999", "country": "United Kingdom", "notes": "Also 112 (EU standard)"},
    "GD": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Grenada"},
    "GE": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Georgia"},
    "GH": {"police": "191", "ambulance": "193", "fire": "192", "universal": None, "country": "Ghana"},
    "GM": {"police": "117", "ambulance": "116", "fire": "118", "universal": None, "country": "Gambia"},
    "GN": {"police": "117", "ambulance": "118", "fire": "118", "universal": None, "country": "Guinea"},
    "GQ": {"police": "114", "ambulance": "115", "fire": "116", "universal": None, "country": "Equatorial Guinea"},
    "GR": {"police": "100", "ambulance": "166", "fire": "199", "universal": "112", "country": "Greece"},
    "GT": {"police": "110", "ambulance": "123", "fire": "122", "universal": None, "country": "Guatemala"},
    "GW": {"police": "117", "ambulance": "119", "fire": "118", "universal": None, "country": "Guinea-Bissau"},
    "GY": {"police": "911", "ambulance": "913", "fire": "912", "universal": None, "country": "Guyana"},
    "HN": {"police": "199", "ambulance": "195", "fire": "198", "universal": "911", "country": "Honduras"},
    "HR": {"police": "192", "ambulance": "194", "fire": "193", "universal": "112", "country": "Croatia"},
    "HT": {"police": "114", "ambulance": "116", "fire": "115", "universal": None, "country": "Haiti"},
    "HU": {"police": "107", "ambulance": "104", "fire": "105", "universal": "112", "country": "Hungary"},
    "ID": {"police": "110", "ambulance": "118", "fire": "113", "universal": "112", "country": "Indonesia"},
    "IE": {"police": "999", "ambulance": "999", "fire": "999", "universal": "112", "country": "Ireland"},
    "IL": {"police": "100", "ambulance": "101", "fire": "102", "universal": None, "country": "Israel"},
    "IN": {"police": "100", "ambulance": "108", "fire": "101", "universal": "112", "country": "India"},
    "IQ": {"police": "104", "ambulance": "122", "fire": "115", "universal": None, "country": "Iraq"},
    "IR": {"police": "110", "ambulance": "115", "fire": "125", "universal": None, "country": "Iran"},
    "IS": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Iceland"},
    "IT": {"police": "112", "ambulance": "118", "fire": "115", "universal": "112", "country": "Italy"},
    "JM": {"police": "119", "ambulance": "110", "fire": "110", "universal": None, "country": "Jamaica"},
    "JO": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Jordan"},
    "JP": {"police": "110", "ambulance": "119", "fire": "119", "universal": None, "country": "Japan", "notes": "Police and fire/ambulance use different numbers. English support is limited."},
    "KE": {"police": "999", "ambulance": "999", "fire": "999", "universal": "999", "country": "Kenya"},
    "KG": {"police": "102", "ambulance": "103", "fire": "101", "universal": None, "country": "Kyrgyzstan"},
    "KH": {"police": "117", "ambulance": "119", "fire": "118", "universal": None, "country": "Cambodia"},
    "KI": {"police": "992", "ambulance": "994", "fire": "993", "universal": None, "country": "Kiribati"},
    "KM": {"police": "17", "ambulance": "15", "fire": "18", "universal": None, "country": "Comoros"},
    "KN": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Saint Kitts and Nevis"},
    "KP": {"police": "819", "ambulance": "819", "fire": "819", "universal": None, "country": "North Korea"},
    "KR": {"police": "112", "ambulance": "119", "fire": "119", "universal": None, "country": "South Korea"},
    "KW": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Kuwait"},
    "KZ": {"police": "102", "ambulance": "103", "fire": "101", "universal": "112", "country": "Kazakhstan"},
    "LA": {"police": "191", "ambulance": "195", "fire": "190", "universal": None, "country": "Laos"},
    "LB": {"police": "112", "ambulance": "140", "fire": "175", "universal": None, "country": "Lebanon"},
    "LC": {"police": "999", "ambulance": "911", "fire": "911", "universal": None, "country": "Saint Lucia"},
    "LI": {"police": "117", "ambulance": "144", "fire": "118", "universal": "112", "country": "Liechtenstein"},
    "LK": {"police": "119", "ambulance": "110", "fire": "111", "universal": None, "country": "Sri Lanka"},
    "LR": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Liberia"},
    "LS": {"police": "123", "ambulance": "121", "fire": "122", "universal": None, "country": "Lesotho"},
    "LT": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Lithuania"},
    "LU": {"police": "113", "ambulance": "112", "fire": "112", "universal": "112", "country": "Luxembourg"},
    "LV": {"police": "112", "ambulance": "113", "fire": "112", "universal": "112", "country": "Latvia"},
    "LY": {"police": "193", "ambulance": "190", "fire": "191", "universal": None, "country": "Libya"},
    "MA": {"police": "19", "ambulance": "15", "fire": "15", "universal": None, "country": "Morocco"},
    "MC": {"police": "17", "ambulance": "18", "fire": "18", "universal": "112", "country": "Monaco"},
    "MD": {"police": "902", "ambulance": "903", "fire": "901", "universal": "112", "country": "Moldova"},
    "ME": {"police": "122", "ambulance": "124", "fire": "123", "universal": "112", "country": "Montenegro"},
    "MG": {"police": "117", "ambulance": "118", "fire": "118", "universal": None, "country": "Madagascar"},
    "MK": {"police": "192", "ambulance": "194", "fire": "193", "universal": "112", "country": "North Macedonia"},
    "ML": {"police": "17", "ambulance": "15", "fire": "18", "universal": None, "country": "Mali"},
    "MM": {"police": "199", "ambulance": "192", "fire": "191", "universal": None, "country": "Myanmar"},
    "MN": {"police": "102", "ambulance": "103", "fire": "101", "universal": None, "country": "Mongolia"},
    "MR": {"police": "17", "ambulance": "18", "fire": "18", "universal": None, "country": "Mauritania"},
    "MT": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Malta"},
    "MU": {"police": "999", "ambulance": "999", "fire": "115", "universal": None, "country": "Mauritius"},
    "MV": {"police": "119", "ambulance": "102", "fire": "118", "universal": None, "country": "Maldives"},
    "MW": {"police": "997", "ambulance": "998", "fire": "999", "universal": None, "country": "Malawi"},
    "MX": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Mexico"},
    "MY": {"police": "999", "ambulance": "999", "fire": "994", "universal": "999", "country": "Malaysia"},
    "MZ": {"police": "119", "ambulance": "117", "fire": "198", "universal": None, "country": "Mozambique"},
    "NA": {"police": "10111", "ambulance": "10177", "fire": "2032270", "universal": None, "country": "Namibia"},
    "NE": {"police": "17", "ambulance": "15", "fire": "18", "universal": None, "country": "Niger"},
    "NG": {"police": "199", "ambulance": "199", "fire": "199", "universal": "112", "country": "Nigeria"},
    "NI": {"police": "118", "ambulance": "128", "fire": "115", "universal": None, "country": "Nicaragua"},
    "NL": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Netherlands"},
    "NO": {"police": "112", "ambulance": "113", "fire": "110", "universal": "112", "country": "Norway"},
    "NP": {"police": "100", "ambulance": "102", "fire": "101", "universal": None, "country": "Nepal"},
    "NZ": {"police": "111", "ambulance": "111", "fire": "111", "universal": "111", "country": "New Zealand"},
    "OM": {"police": "9999", "ambulance": "9999", "fire": "9999", "universal": "9999", "country": "Oman"},
    "PA": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Panama"},
    "PE": {"police": "105", "ambulance": "117", "fire": "116", "universal": None, "country": "Peru"},
    "PG": {"police": "112", "ambulance": "111", "fire": "110", "universal": None, "country": "Papua New Guinea"},
    "PH": {"police": "117", "ambulance": "911", "fire": "911", "universal": "911", "country": "Philippines"},
    "PK": {"police": "15", "ambulance": "115", "fire": "16", "universal": None, "country": "Pakistan"},
    "PL": {"police": "997", "ambulance": "999", "fire": "998", "universal": "112", "country": "Poland"},
    "PT": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Portugal"},
    "PY": {"police": "911", "ambulance": "911", "fire": "132", "universal": None, "country": "Paraguay"},
    "QA": {"police": "999", "ambulance": "999", "fire": "999", "universal": "999", "country": "Qatar"},
    "RO": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Romania"},
    "RS": {"police": "192", "ambulance": "194", "fire": "193", "universal": "112", "country": "Serbia"},
    "RU": {"police": "102", "ambulance": "103", "fire": "101", "universal": "112", "country": "Russia"},
    "RW": {"police": "112", "ambulance": "912", "fire": "111", "universal": None, "country": "Rwanda"},
    "SA": {"police": "999", "ambulance": "997", "fire": "998", "universal": None, "country": "Saudi Arabia"},
    "SB": {"police": "999", "ambulance": "911", "fire": "999", "universal": None, "country": "Solomon Islands"},
    "SC": {"police": "999", "ambulance": "151", "fire": "999", "universal": None, "country": "Seychelles"},
    "SD": {"police": "999", "ambulance": "999", "fire": "999", "universal": None, "country": "Sudan"},
    "SE": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Sweden"},
    "SG": {"police": "999", "ambulance": "995", "fire": "995", "universal": None, "country": "Singapore"},
    "SI": {"police": "113", "ambulance": "112", "fire": "112", "universal": "112", "country": "Slovenia"},
    "SK": {"police": "158", "ambulance": "155", "fire": "150", "universal": "112", "country": "Slovakia"},
    "SL": {"police": "999", "ambulance": "999", "fire": "019", "universal": None, "country": "Sierra Leone"},
    "SM": {"police": "112", "ambulance": "118", "fire": "115", "universal": "112", "country": "San Marino"},
    "SN": {"police": "17", "ambulance": "18", "fire": "18", "universal": None, "country": "Senegal"},
    "SO": {"police": "888", "ambulance": "999", "fire": "555", "universal": None, "country": "Somalia"},
    "SR": {"police": "115", "ambulance": "113", "fire": "115", "universal": None, "country": "Suriname"},
    "SS": {"police": "999", "ambulance": "999", "fire": "999", "universal": None, "country": "South Sudan"},
    "ST": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "São Tomé and Príncipe"},
    "SV": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "El Salvador"},
    "SY": {"police": "112", "ambulance": "110", "fire": "113", "universal": None, "country": "Syria"},
    "SZ": {"police": "999", "ambulance": "977", "fire": "933", "universal": None, "country": "Eswatini"},
    "TD": {"police": "17", "ambulance": "18", "fire": "18", "universal": None, "country": "Chad"},
    "TG": {"police": "117", "ambulance": "118", "fire": "118", "universal": None, "country": "Togo"},
    "TH": {"police": "191", "ambulance": "1669", "fire": "199", "universal": None, "country": "Thailand", "notes": "Tourist police: 1155 (English speaking)"},
    "TJ": {"police": "02", "ambulance": "03", "fire": "01", "universal": None, "country": "Tajikistan"},
    "TL": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Timor-Leste"},
    "TM": {"police": "02", "ambulance": "03", "fire": "01", "universal": None, "country": "Turkmenistan"},
    "TN": {"police": "197", "ambulance": "190", "fire": "198", "universal": None, "country": "Tunisia"},
    "TO": {"police": "922", "ambulance": "933", "fire": "928", "universal": None, "country": "Tonga"},
    "TR": {"police": "155", "ambulance": "112", "fire": "110", "universal": "112", "country": "Turkey"},
    "TT": {"police": "999", "ambulance": "990", "fire": "990", "universal": None, "country": "Trinidad and Tobago"},
    "TV": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "Tuvalu"},
    "TW": {"police": "110", "ambulance": "119", "fire": "119", "universal": None, "country": "Taiwan"},
    "TZ": {"police": "112", "ambulance": "114", "fire": "115", "universal": None, "country": "Tanzania"},
    "UA": {"police": "102", "ambulance": "103", "fire": "101", "universal": "112", "country": "Ukraine"},
    "UG": {"police": "999", "ambulance": "112", "fire": "112", "universal": None, "country": "Uganda"},
    "US": {"police": "911", "ambulance": "911", "fire": "911", "universal": "911", "country": "United States"},
    "UY": {"police": "109", "ambulance": "105", "fire": "104", "universal": None, "country": "Uruguay"},
    "UZ": {"police": "102", "ambulance": "103", "fire": "101", "universal": None, "country": "Uzbekistan"},
    "VA": {"police": "112", "ambulance": "118", "fire": "115", "universal": "112", "country": "Vatican City"},
    "VC": {"police": "999", "ambulance": "999", "fire": "999", "universal": "999", "country": "Saint Vincent and the Grenadines"},
    "VE": {"police": "171", "ambulance": "171", "fire": "171", "universal": "171", "country": "Venezuela"},
    "VN": {"police": "113", "ambulance": "115", "fire": "114", "universal": None, "country": "Vietnam"},
    "VU": {"police": "112", "ambulance": "112", "fire": "112", "universal": "112", "country": "Vanuatu"},
    "WS": {"police": "994", "ambulance": "996", "fire": "993", "universal": None, "country": "Samoa"},
    "XK": {"police": "192", "ambulance": "194", "fire": "193", "universal": "112", "country": "Kosovo"},
    "YE": {"police": "199", "ambulance": "191", "fire": "175", "universal": None, "country": "Yemen"},
    "ZA": {"police": "10111", "ambulance": "10177", "fire": "10177", "universal": "112", "country": "South Africa"},
    "ZM": {"police": "999", "ambulance": "992", "fire": "993", "universal": None, "country": "Zambia"},
    "ZW": {"police": "995", "ambulance": "994", "fire": "993", "universal": None, "country": "Zimbabwe"},
}

def main():
    out_dir = os.path.join(os.path.dirname(__file__), '..', 'data')
    os.makedirs(out_dir, exist_ok=True)
    
    out_path = os.path.join(out_dir, 'emergency-numbers.json')
    
    output = {
        "version": "1.0.0",
        "lastUpdated": "2026-03-30",
        "source": "Wikipedia, ITU, government sources",
        "count": len(EMERGENCY_NUMBERS),
        "countries": EMERGENCY_NUMBERS
    }
    
    with open(out_path, 'w') as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
    
    print(f"✅ Built emergency numbers for {len(EMERGENCY_NUMBERS)} countries → {out_path}")
    
    # Stats
    with_universal = sum(1 for v in EMERGENCY_NUMBERS.values() if v.get('universal'))
    with_notes = sum(1 for v in EMERGENCY_NUMBERS.values() if v.get('notes'))
    print(f"   {with_universal} countries with universal number")
    print(f"   {with_notes} countries with additional notes")

if __name__ == '__main__':
    main()
